import {
  ImgApelac,
  ImgBiolinks,
  ImgBlufstein,
  ImgCerema,
  ImgCruzDelSur,
  ImgEmptyDefault,
  ImgFootloose,
  ImgInppares,
  ImgLaPositivaSeguros,
  ImgLaPositivaVida,
  ImgLazzosComerciales,
  ImgLogistas,
  ImgMedifon,
  ImgMovilBus,
  ImgMultident,
  ImgOltursa,
  ImgQuirovida,
  ImgRenzoCosta,
  ImgRimacCompany,
  ImgRimacSeguros,
  ImgRotarInternational,
  ImgSmartFit,
  ImgSugo,
  ImgTinnitus,
  ImgTransportesOltursa,
  ImgUnident,
  ImgUnilabs,
} from "../images";

export const companies = [
  {
    type: "laboratory",
    image: ImgInppares,
    title: "Lab. INPPARES",
    benefits: [
      "ALCANCE DEL CONVENIO:\n",
      "Dirigido al personal militar en actividad o retiro, personal civil en situación de actividad, así como sus familiares directos (cónyuge, hijos, padres y hermanos); debidamente acreditados.\n",
      "FORMA DE ACREDITACIÓN:\n",
      "a)\tPresentación del carnet de identificación personal militar o civil CIP\n",
      "b)\tPresentación del carnet de identificación familiar CIF (cónyuge, hijos, padres y hermanos).\n",
      "c)\tPara el caso de familiares directos, que no posean el Carnet de Identidad Familiar (CIF), presentarán el (DNI) y el titular deberá de acompañarlos para que acredite el vínculo familiar.\n",
      "BENEFICIO \n",
      "a)\tDescuento del 10% de sobre los costos de las tarifas regulares, EN CONSULTAS EN LAS DIFERENTES ESPECIALIDADES LA SEDE DE JESÚS MARÍA. Anexo 01\n",
      "b)\tDescuento entre el 5% y 10% sobre los costos de las tarifas regulares en, EXÁMENES DE LABORATORIO Y PROCEDIMIENTOS CLÍNICOS, realizados en la sede de Jesús María. Anexo 01\n",
      "c)\tDescuento del 5% de sobre los costos de las tarifas regulares en sedes de LOS OLIVOS Y SAN JUAN DE LURIGANCHO, EN CONSULTAS, EXÁMENES DE LABORATORIO Y PROCEDIMIENTOS CLÍNICOS, en las diferentes especialidades sede.  Anexo 01\n",
    ],
  },

  {
    type: "clinic",
    image: ImgMedifon,
    title: "MEDIFON",
    benefits: [
      "ALCANCE DEL CONVENIO:",
      "Dirigido al personal militar en actividad o retiro, personal civil en situación de actividad, así como sus familiares directos (cónyuge, hijos, padres y hermanos); debidamente acreditados sin límite de edad.",
      "FORMA DE ACREDITACIÓN:\n",
      "Presentación del carnet de identificación personal militar o civil CIP\n",
      "Presentación del carnet de identificación familiar CIF (cónyuge, hijos, padres y hermanos).\n",
      "Para el caso de familiares directos, que no posean el Carnet de Identidad Familiar (CIF), presentarán el (DNI) y el titular deberá de acompañarlos para que acredite el vínculo familiar.\n",
      "BENEFICIO \n",
      "Implementará el acceso al beneficio a través del call center y presencial en las sedes de Miraflores, Jesús María, Los Olivos, San Borja, San juan de Lurigancho, San juan de Miraflores, san miguel y Cercado de Lima, en todos sus servicios, procedimientos y dispositivos médicos auditivos ofrecidos.  \n",
      "Otorgará el valor de $150 dólares americanos, de descuento sobre los costos de las tarifas regulares, en dispositivos AUDÍFONOS MEDICADOS de la marca BELTONE.\n",
      "Otorgará garantía por un año, recalibraciones, limpiezas y mantenimiento ilimitados, así como dotación de seis baterías, en los dispositivos AUDÍFONOS MEDICADOS de la marca BELTONE.\n",
      "Otorgará el 25% de descuento sobre los costos de las tarifas regulares, en baterías, pilas, accesorios de limpieza, en las diferentes sedes.\n",
      "Otorgará el valor de cien s/100 soles, en el costo por consulta especializada previa cita en la especialidad de otorrinolaringología.\n",
      "Otorgará acceso gratuito a los servicios de audiológicos (audiometría y otoscopía), previa cita.\n",
      "Otorgará a los BENEFICIARIOS de “EL EJÉRCITO” el valor de $150 ciento cincuenta dólares americanos de descuento sobre el costo tarifa regular de los DISPOSITIVOS VIBRADORES ÓSEOS.\n",
      "Otorgará el valor de $2000 dos mil dólares americanos de descuento sobre el costo tarifa regular del dispositivo medico a largo plazo, IMPLANTE COCLEAR, en lo correspondiente a la colocación quirúrgica (clínica, operación, anestesiólogo, equipo, post operatorio, cincuenta terapías de lenguaje y otros).\n",
      "Los beneficios antes indicados serán en todas las sedes de MEDIFON, según Anexo 01.\n",
    ],
  },

  {
    type: "laboratory",
    image: ImgBiolinks,
    title: "LAB. 'BIOLINKS'",
    benefits: [
      "ALCANCE DEL CONVENIO:\n",
      "Dirigido al personal militar en actividad o retiro, personal civil en situación de actividad, así como sus familiares directos (cónyuge, hijos, padres y hermanos); debidamente acreditados.\n",
      "FORMA DE ACREDITACIÓN:\n",
      "Presentación del carnet de identificación personal militar o civil CIP\n",
      "Presentación del carnet de identificación familiar CIF (cónyuge, hijos, padres y hermanos).\n",
      "Para el caso de familiares directos, que no posean el Carnet de Identidad Familiar (CIF), presentarán el (DNI) y el titular deberá de acompañarlos para que acredite el vínculo familiar\n",
      "BENEFICIO \n",
      "a)\tAcceso a costo diferenciado de porcentaje de descuento sobre la tarifa regular, en todas sus sedes propias y sedes con colaboradores con alianzas estratégicas, de los exámenes de laboratorios que se indican:\n",
      "•\tPruebas de Paternidad Parentesco.  \n",
      "•\tOncológicos aérea diagnostico\n",
      "•\tÁreas infecciosas\n",
      "\n",
      "b)\tRealización de citas mediante:\n",
      "•\tForma PRESENCIAL, en las sedes siguientes:\n",
      "-\tSede Lima Av. Javier Prado Oeste 844 Magdalena y Av. Carlos Izaguirre 736, Los Olivos.\n",
      "-\tSede Trujillo, Av. Jesús de Nazareth 364 Urb. San Andrés.\n",
      "-\tSede Huancayo, Jr. Parra delo Riego 375-399 El Tambo.\n",
      "-\tSede Arequipa, Av. Zamacola 203, Yanahuara.\n",
      "-\tSedes en otras provincias del Perú con colaboradores en convenio con Biolinks. \n",
      "\n",
      "•\tInformes a los teléfonos:  2614411 y 2614412, debiendo acreditarse el día de la cita con el CIP, CIF y/o DNI, según sea el caso, y la presentación de las órdenes médicas respectivas.\n",
      "\n",
      "Correo electrónico adn@biolinksperù.com – www.biolinksperu.com.\n",
    ],
  },

  {
    type: "laboratory",
    image: ImgUnilabs,
    title: "Lab. UNILABS",
    benefits: [
      "ALCANCE DEL CONVENIO:\n",
      "Dirigido al personal militar en actividad o retiro, personal civil en situación de actividad, así como sus familiares directos (cónyuge, hijos, padres y hermanos); debidamente acreditados.\n",
      "FORMA DE ACREDITACIÓN:\n",
      "a)\tPresentación del carnet de identificación personal militar o civil CIP\n",
      "b)\tPresentación del carnet de identificación familiar CIF (cónyuge, hijos, padres y hermanos).\n",
      "c)\tPara el caso de familiares directos, que no posean el Carnet de Identidad Familiar (CIF), presentarán el (DNI) y el titular deberá de acompañarlos para que acredite el vínculo familiar.\n",
      "BENEFICIO \n",
      "a)\tAcceso al 40% de descuento sobre la tarifa regular, de los exámenes de laboratorio de rutina; ANEXO 01\n",
      "b)\tAcceso a la tarifa hospitalaria en el Centro CIMEDIC en las pruebas de diagnóstico por imágenes (tomografía, resonancia magnética). ANEXO 01. \n",
      "c)\tAcceso al 10% de descuento sobre la tarifa base, de los denominados exámenes de Anatomía Patológica (citología y quirúrgicos, inmunohistoquímica – marcadores inmunohistoquímicos, biología molecular, citometría de flujo, genética) y pruebas especiales; según el detalle descrito en el ANEXO 01.\n",
      "d)\tRealización de citas mediante:\n",
      "•\tForma PRESENCIAL\n",
      "•\tVía CALL CENTER, debiendo acreditarse el día de la cita con el CIP, CIF y/o DNI, según sea el caso, y la presentación de las ordenes médicas emitidas por el HMC o centros de salud privados.\n",
    ],
  },
  {
    type: "transport",
    image: ImgOltursa,
    title: "OLTURSA",
    benefits: [
      "ALCANCE DEL CONVENIO:\n",
      "Dirigido al personal militar en actividad o retiro, personal civil en situación de actividad, así como sus familiares directos (cónyuge, hijos, padres y hermanos); debidamente acreditados.\n",
      "FORMA DE ACREDITACIÓN:\n",
      "a)\tPresentación del carnet de identificación personal militar o civil CIP\n",
      "b)\tPresentación del carnet de identificación familiar CIF (cónyuge, hijos, padres).\n",
      "c)\tPara el caso de familiares directos, que no posean el Carnet de Identidad Familiar (CIF), presentarán el (DNI) y el titular deberá de acompañarlos para que acredite el vínculo familiar.\n",
      "d)\tDeberá de presentar copia de CIP al momento de la compra.\n",
      "BENEFICIO \n",
      "a)\tNo aplica para compras por página web, call center \n",
      "b)\tAcceso los 364 días del año, de forma PRESENCIAL\n",
      "c)\tAcceso al 15% de descuento sobre la tarifa regular, en transporte interprovincial de pasajeros (bus cama 140,160,180), hacia cualquiera de los destinos.\n",
      "d)\tAcceso al 10% de descuento sobre la tarifa \tregular, en el servicio de envió a través de Servicio expreso y Servicio consolidado, en todos sus destinos.\n",
      "e)\tCostos diferenciados, de transporte del tipo CORPORATIVO o transporte TURÍSTICO, previa evaluación de OLTURSA.\n",
    ],
  },
  {
    type: "commercial-shop",
    image: ImgFootloose,
    title: "Calzado FOOTLOOSE",
    benefits: [
      "ALCANCE DEL CONVENIO:\n",
      "Dirigido al personal militar en actividad o retiro, personal civil en situación de actividad, así como sus familiares directos (cónyuge, hijos, padres y hermanos); debidamente acreditados.\n",
      "FORMA DE ACREDITACIÓN:\n",
      "a)\tPresentación del carnet de identificación personal militar o civil CIP\n",
      "b)\tPresentación del carnet de identificación familiar CIF (cónyuge, hijos, padres).\n",
      "BENEFICIO \n",
      "a)\tExclusivo para compras presenciales.\n",
      "b)\tNo aplica compras por web, app, o Facebook\n",
      "c)\tDescuento del 15% en marcas propias según relación anexo \n",
      "d)\tDescuento del 10% en todas marcas diferentes.\n",
      "e)\tTiendas ubicadas en todos los centros comerciales \n",
    ],
  },
  {
    type: "clinic",
    image: ImgTinnitus,
    title: "TINNITUS",
    benefits: [
      "ALCANCE DEL CONVENIO:\n",
      "Dirigido al personal militar en actividad o retiro, personal civil en situación de actividad, así como sus familiares directos (cónyuge, hijos, padres y hermanos); debidamente acreditados sin límite de edad.\n",
      "FORMA DE ACREDITACIÓN:\n",
      "Presentación del carnet de identificación personal militar o civil CIP\n",
      "Presentación del carnet de identificación familiar CIF (cónyuge, hijos, padres).\n",
      "BENEFICIO \n",
      "Consultas e informes a través del celular y WhatsApp: 980688232, así como correo electrónico comercial@grupoinfinitech.com y presencial en la Av. Canadá Nº 3630, consultorio 205 San Borja en todos sus servicios, procedimientos y dispositivos médicos auditivos ofrecidos.  \n",
      "Descuento del 30% en audífonos medicados programables que comercialice la empresa.\n",
      "Gratis Kit de limpieza por la compra de audífonos medicados. \n",
      "Descuento del 20% de en servicios de audiología, psicología nutrición.\n",
    ],
  },
  {
    type: "commercial-shop",
    image: ImgRenzoCosta,
    title: "RENZO COSTA",
    benefits: [
      "ALCANCE DEL CONVENIO:\n",
      "Dirigido al personal militar en actividad o retiro, personal civil en situación de actividad, así como sus familiares directos (cónyuge, hijos, padres y hermanos); debidamente acreditados sin límite de edad.\n",
      "FORMA DE ACREDITACIÓN:\n",
      "a)\tPresentación del carnet de identificación personal militar o civil CIP\n",
      "b)\tPresentación del carnet de identificación familiar CIF (cónyuge, hijos, padres).\n",
      "BENEFICIO \n",
      "a)\tExclusivo para compras presenciales.\n",
      "b)\tNo aplica compras por web, app, o Facebook\n",
      "c)\tDescuento del 10% en todos los productos tiendas propias según relación anexo\n",
      "d)\tDescuento del 5% en todos los productos, toda la cadena de tiendas a nivel nacional (centros comerciales), anexo\n",
    ],
  },
  {
    image: ImgLazzosComerciales,
    title: "LAZZOS COMERCIALES",
    benefits: [
      "\t20% DE DESCUENTO SOBRE EL PRECIO DE ETIQUETA EN TODAS LAS TIENDAS MOSSA SHOES Y VISANO TIENDA FÍSICO Y VIRTUAL\n",
      "BENEFICIARIOS:",
      "PERSONAL MILITAR EN ACTIVIDAD, RETIRO Y FAMILIARES DIRECTOS EMPLEADOS CIVILES  Y FAMILIARES DIRECTOS",
    ],
  },
  {
    type: "clinic",
    image: ImgMultident,
    title: "MULTIDENT",
    benefits: [
      "ALCANCE DEL CONVENIO:\n",
      "Dirigido al personal militar en actividad o retiro, personal civil en situación de actividad, así como sus familiares directos (cónyuge, hijos, padres y hermanos); debidamente acreditados sin límite de edad.\n",
      "FORMA DE ACREDITACIÓN:\n",
      "Presentación del carnet de identificación personal militar o civil CIP\n",
      "Presentación del carnet de identificación familiar CIF (cónyuge, hijos, padres y hermanos).\n",
      "Para el caso de familiares directos, que no posean el Carnet de Identidad Familiar (CIF), presentarán el (DNI) y el titular deberá de acompañarlos para que acredite el vínculo familiar.\n",
      "BENEFICIO \n",
      "Acceso a los distintos servicios odontológicos ofrecidos, a través de costos diferenciados, mediante porcentaje de descuento sobre las tarifas regulares, de acuerdo a lo establecido en el Anexo 01.\n",
      "Implementará a través la programación a través del call center, y de forma presencial en todas sedes a nivel nacional, y en todos sus horarios.\n",
      "Servicios de emergencias dentales, las 24 horas del día, los 7 días de la semana en la sede de la Av. César Vallejo N° 1560 - Lince y en todas las sedes a nivel nacional en horario de atención.\n",
      "CONSULTA GRATUITA \n",
      "Profilaxis y destartraje de cortesía.\n",
    ],
  },
  {
    type: "transport",
    image: ImgMovilBus,
    title: "Movil Bus",
    benefits: [
      "ALCANCE DEL CONVENIO:\n",
      "Dirigido al personal militar en actividad o retiro, personal civil en situación de actividad, así como sus familiares directos (cónyuge, hijos, padres y hermanos); debidamente acreditados sin límite de edad.\n",
      "FORMA DE ACREDITACIÓN:\n",
      "a)\tPresentación del carnet de identificación personal militar o civil CIP\n",
      "b)\tPresentación del carnet de identificación familiar CIF (cónyuge, hijos, Padres).\n",
      "c)\tPara el caso de familiares directos, que no posean el Carnet de Identidad Familiar (CIF), presentarán el (DNI) y el titular deberá de acompañarlos para que acredite el vínculo familiar.\n",
      "d)\tDeberá de presentar copia de CIP al momento de la compra.\n",
      "BENEFICIO \n",
      "a)\tNo aplica para compras por página web, call center \n",
      "b)\tAcceso los 364 días del año, de forma PRESENCIAL\n",
      "c)\tAcceso al 20% de descuento sobre la tarifa regular, en transporte interprovincial de pasajeros (económico, premier, presidencial, ejecutivo, vip), hacia cualquiera de los destinos.\n",
      "d)\tAcceso al 30% de descuento sobre la tarifa regular, en el servicio de envió a través de MOVIL CARGA y MOVIL COURIER,\tque inicien en provincias (hacia Lima) a excepción de Lima como origen.\n",
      "e)\tAcceso al 15% de descuento sobre la tarifa regular, en el servicio de envió a través de MOVIL CARGA y MOVIL COURIER que inicien en Lima, hacia cualquiera de los destinos ofrecidos.\n",
      "f)\tCostos diferenciados, de transporte del tipo CORPORATIVO o transporte TURÍSTICO, previa evaluación de MOVILBUS.\n",
    ],
  },
  {
    type: "gym",
    image: ImgSmartFit,
    title: "Smart Fit",
    benefits: [
      "ALCANCE DEL CONVENIO:\n",
      "Dirigido al personal militar en actividad o retiro, personal civil en situación de actividad, así como sus familiares directos (cónyuge, hijos, padres y hermanos); debidamente acreditados sin límite de edad.\n",
      "FORMA DE ACREDITACIÓN:\n",
      "Presentación del carnet de identificación personal militar o civil CIP\n",
      "Presentación del carnet de identificación familiar CIF (cónyuge, hijos, padres y hermanos).\n",
      "Para el caso de familiares directos, que no posean el Carnet de Identidad Familiar (CIF), presentarán el (DNI) y el titular deberá de acompañarlos para que acredite el vínculo familiar.\n",
      "BENEFICIO \n",
      "Acceso PLAN BLACK corporativo, con un costo de s/99.90, el cual otorga los siguientes beneficios: \n",
      "•\tExoneración del pago único de “Matrícula”, mediante pago a cuenta de tarjeta crédito o débito.\n",
      "•\tExoneración del pago anual de “Mantenimiento”.\n",
      "•\tExoneración del pago de la penalidad por resolución anticipada contemplada en la cláusula “Cancelación y Expulsión”.\n",
      "•\tEntrenamiento en cualquier sede del Perú y Latinoamérica.\n",
      "•\tInvitación amigos y familiares hasta 5 veces al mes.\n",
      "•\tAcceso a sillones de masajes.\n",
      "•\tAcceso de manera ilimitada a la plataforma Virtual SMART FIT GO.\n",
      "•\tLibre de elección de fechas de entrenamiento, mínimo un mes.\n",
    ],
  },
  {
    type: "clinic",
    image: ImgApelac,
    title: "Apelac",
    benefits: [
      "ALCANCE DEL CONVENIO:\n",
      "Dirigido al personal militar en actividad o retiro, personal civil en situación de actividad, así como sus familiares directos (cónyuge, hijos, padres y hermanos); debidamente acreditados sin límite de edad.\n",
      "FORMA DE ACREDITACIÓN:\n",
      "Presentación del carnet de identificación personal militar o civil CIP\n",
      "Presentación del carnet de identificación familiar CIF (cónyuge, hijos, padres y hermanos).\n",
      "Para el caso de familiares directos, que no posean el Carnet de Identidad Familiar (CIF), presentarán el (DNI) y el titular deberá de acompañarlos para que acredite el vínculo familiar.\n",
      "BENEFICIO \n",
      "Servicios psicopedagógicos, especializados en problemas de lenguaje, aprendizaje y conducta, a través de tarifas especiales, mediante porcentaje de descuento, según grado de el BENEFICIARIO, así como costos diferenciados en las sedes de APEPLAC. Anexo A – SURCO y Anexo B – RÌMAC\n",
      "Direcciones y citas telefónicas \n",
      "Sede Surco Mariscal Castilla 1170 - Teléfonos 4356989 y 990436788.\n",
      "Sede Rímac Calle Fray Ramón Rojas 191 – Teléfono: 990436788.\n",
    ],
  },
  {
    type: "commercial-shop",
    image: ImgLogistas,
    title: "Logistas",
    benefits: [
      "•\tSERVICIOS DE MANTENIMIENTO VEHICULAR CORRECTIVOS\n",
      "COSTOS DIFERENCIADOS DE LA TARIFA REGULAR, SEGÚN TARIFARIO",
      "BENEFICIARIOS:",
      "PERSONAL MILITAR EN ACTIVIDAD, RETIRO Y FAMILIARES DIRECTOS EMPLEADOS CIVILES  Y FAMILIARES DIRECTOS",
    ],
  },
  {
    type: "commercial-shop",
    image: ImgSugo,
    title: "Sugo",
    benefits: [
      "ACCESO EN LÍNEA EN SUS PLATAFORMAS EN COMPRAS DE CONSUMO SOSTENIBLE\n",
      "HASTA 50% DEL PRECIO EN EL MERCADO\n",
      "BENEFICIARIOS:",
      "PERSONAL MILITAR EN ACTIVIDAD, RETIRO Y FAMILIARES DIRECTOS EMPLEADOS CIVILES  Y FAMILIARES DIRECTOS",
    ],
  },
  {
    type: "clinic",
    image: "",
    title: "Clínica Auna",
    benefits: ["POR FIRMAR"],
  },
  {
    type: "financial",
    image: "",
    title: "Financ. Efectiva",
    benefits: ["POR FIRMAR"],
  },
  {
    type: "financial",
    image: "",
    title: "Financ. Finantel",
    benefits: [
      "ALCANCE DEL CONVENIO:\n",
      "Dirigido al personal militar en situación de actividad o retiro y personal civil en situación de actividad o cesante.\t.\n",
      "TASA DE INTERES ANUAL:\n",
      "Según clasificación de SBS de 18% a 22%\n",
      "Mejores tasas por campañas impulsadas por la FINANCIERA de acuerdo al análisis del mercado\n",
    ],
  },
  {
    type: "financial",
    image: "",
    title: "FINANC. LA REHABILITADORA",
    benefits: [
      "ALCANCE DEL CONVENIO:\n",
      "Dirigido al personal militar en situación de actividad o retiro y personal civil en situación de actividad o cesante.\t.\n",
      "TASA DE INTERES ANUAL:\n",
      "Según clasificación de SBS de 18.5% a 24.6%\n",
      "Mejores tasas por campañas impulsadas por la FINANCIERA de acuerdo al análisis del mercado\n",
    ],
  },
  {
    type: "hotel",
    image: "",
    title: "HOTEL CASA ANDINA",
    benefits: [
      "ALCANCE DEL CONVENIO:\n",
      "Dirigido al personal militar en actividad o retiro, personal civil en situación de actividad, así como sus familiares directos (cónyuge, hijos, padres); debidamente acreditados.\n",
      "FORMA DE ACREDITACIÓN:\n",
      "Presentación del carnet de identificación personal militar o civil CIP\n",
      "Presentación del carnet de identificación familiar CIF (cónyuge, hijos, padres y hermanos).\n",
      "Para el caso de familiares directos, que no posean el Carnet de Identidad Familiar (CIF), presentarán el (DNI) y el titular deberá de acompañarlos para que acredite el vínculo familiar.\n",
      "3)\tBENEFICIO \n",
      "a)\tBrindará a los BENEFICIARIOS, acceso a descuentos sobre la tarifa regular, de hasta 30%, en los alojamientos propios y asociados, ubicados a nivel nacional, vigentes al momento de la reserva, según relación actualizada, de forma trimestral, ANEXO 01.\n",
      "b)\tEl acceso a los servicios hoteleros ofrecidos, a través de porcentaje de descuento sobre las tarifas regulares, otorgados EXCLUSIVAMENTE mediante la web https://www.casa-andina.com/es/ofertas/ejercitoperu , canales de atención a través de correo electrónico centraldereservas@casa-andina.com y call center (01) 3916500.\n",
      "c)\tEl código de acceso al descuento es EJERCITOPERU22.\n",
      "d)\tValidará indispensablemente, al BENEFICIARIO, mediante la presentación física del respectivo Carnet de Identidad Personal del titular (CIP), y familiares directos mediante presentación del Carnet de Identificación Familiar (CIF); al momento de ingreso al hotel.\n",
      "e)\tEn caso el BENEFICIARIO, no pueda acreditar que es personal de “EL EJÉRCITO”, “CASA ANDINA” informará a dicho huésped, que no es acreedor al descuento por convenio y además se reserva el derecho de cobrar el monto vigente al momento del check – in.\n",
      "f)\tLas reservas realizadas son de tarifas NO REEMBOLSABLE.\n",
      "g)\tAl finalizar el pago, cabe mencionar que se aplicará el 10% a la tarifa inicial por el cargo correspondiente a servicios y el 18% de impuestos de ley vigentes; los mismos que podrán variar de acuerdo a las regulaciones gubernamentales.\n",
    ],
  },
  {
    type: "hotel",
    image: "",
    title: "HOTEL COSTA DEL SOL ",
    benefits: [""],
  },
  {
    type: "laboratory",
    image: "",
    title: "Lab. Roe",
    benefits: ["Por Firmar"],
  },
  {
    type: "commercial-shop",
    image: "",
    title: "CALZADO VIZZANO",
    benefits: [
      "ALCANCE DEL CONVENIO:\n",
      "Dirigido al personal militar en actividad o retiro, personal civil en situación de actividad, así como sus familiares directos (cónyuge, hijos, padres); debidamente acreditados.\n",
      "FORMA DE ACREDITACIÓN:\n",
      "a)\tPresentación del carnet de identificación personal militar o civil CIP\n",
      "b)\tPresentación del carnet de identificación familiar CIF (cónyuge, hijos, padres).\n",
      "BENEFICIO \n",
      "a)\tCompras presenciales, solo en tiendas propias. \n",
      "b)\tAplica para compras en tienda virtual, mediante el uso del cupón al momento de hacer el pago\n",
      "\thttps://www.mossashoes.com/\n",
      "\tCupón MOSSAEJE20\n",
      "c)\tDescuento del 15% en marcas propias \n",
      "d)\tDescuento del 10% en todas marcas diferentes.\n",
    ],
  },
];
