import {
  ImgApelac,
  ImgBiolinks,
  ImgBlufstein,
  ImgCerema,
  ImgCruzDelSur,
  ImgEmptyDefault,
  ImgFootloose,
  ImgInppares,
  ImgLaPositivaSeguros,
  ImgLaPositivaVida,
  ImgLazzosComerciales,
  ImgLogistas,
  ImgMedifon,
  ImgMovilBus,
  ImgMultident,
  ImgOltursa,
  ImgQuirovida,
  ImgRenzoCosta,
  ImgRimacCompany,
  ImgRimacSeguros,
  ImgRotarInternational,
  ImgSmartFit,
  ImgSugo,
  ImgTinnitus,
  ImgTransportesOltursa,
  ImgUnident,
  ImgUnilabs,
} from "../images";

export const companies = [
  {
    image: ImgInppares,
    title: "INPPARES",
    benefits: [
      "TARIFAS ESPECIALES 10% DE DESCUENTO SOBRE    PRECIO AL PÚBLICO",
      "BENEFICIARIOS:",
      "PERSONAL MILITAR EN ACTIVIDAD, RETIRO Y FAMILIARES DIRECTOS EMPLEADOS CIVILES  Y FAMILIARES DIRECTOS",
    ],
  },

  {
    image: ImgMedifon,
    title: "MEDIFON",
    benefits: [
      "\tDESCUENTO DE $ 150.00 DÓLARES POR LA COMPRA DE AUDÍFONOS MARCA BELTONE  \n",
      "\t25% DESCUENTO EN REPUESTOS Y ACCESORIOS\n",
      "BENEFICIARIOS:",
      "PERSONAL MILITAR EN ACTIVIDAD, RETIRO Y FAMILIARES DIRECTOS EMPLEADOS CIVILES  Y FAMILIARES DIRECTOS",
    ],
  },

  {
    image: ImgBiolinks,
    title: "LAB. 'BIOLINKS'",
    benefits: [
      "\tPRUEBA DE ADN RECONOCIMIENTO DE PATERNIDAD\n",
      "\tTARIFA CON CONVENIO 20% DESCUENTO\n",
      "\tEXÁMENES DE LABORATORIO CLÍNICO ONCOLÓGICO - ÁREA DE DIAGNÓSTICO.\n",
      "\tEXAMEN DE LABORATORIO CLÍNICO - ÁREAS INFECCIOSAS\n",
      "BENEFICIARIOS:",
      "PERSONAL MILITAR EN ACTIVIDAD, RETIRO Y FAMILIARES DIRECTOS EMPLEADOS CIVILES  Y FAMILIARES DIRECTOS",
    ],
  },

  {
    image: ImgUnilabs,
    title: "UNILABS",
    benefits: [
      "ANÁLISIS CLÍNICOS 40% DE DESCUENTO\n",
      "ANÁLISIS ESPECIALES  10% DE DESCUENTO\n",
      "BENEFICIARIOS:",
      "PERSONAL MILITAR EN ACTIVIDAD, RETIRO Y FAMILIARES DIRECTOS EMPLEADOS CIVILES  Y FAMILIARES DIRECTOS",
    ],
  },
  {
    image: ImgOltursa,
    title: "OLTURSA",
    benefits: [
      "\tSERVICIO DE PASAJERO TODO EL AÑO\n",
      "\tTODOS LOS SERVICIOS Y TODOS LOS DESTINOS 15 % DE DESCUENTO.\n",
      "\tSERVICIO TRANSPORTE DE CORRESPONDENCIA, PAQUETERÍA, ENCOMIENDAS, CARGA LIGERA O MEDIANA 10% DE DESCUENTO.\n",
      "\tLLEVAR COPIA DE CIP-CIF\n",
      "\tDESCUENTOS CORPORATIVOS TARIFAS ESPECIALES\n",
      "BENEFICIARIOS:",
      "PERSONAL MILITAR EN ACTIVIDAD, RETIRO Y FAMILIARES DIRECTOS EMPLEADOS CIVILES  Y FAMILIARES DIRECTOS",
    ],
  },
  {
    image: ImgFootloose,
    title: "FOOTLOOSE",
    benefits: [
      "\t20 % DE DESCUENTO MARCAS PROPIAS Y 10% OTRAS MARCAS",
      "BENEFICIARIOS:",
      "PERSONAL MILITAR EN ACTIVIDAD, RETIRO Y FAMILIARES DIRECTOS EMPLEADOS CIVILES  Y FAMILIARES DIRECTOS",
    ],
  },
  {
    image: ImgTinnitus,
    title: "TINNITUS",
    benefits: [
      "\tAUDÍFONOS MEDICADOS DIGITALES 30% DE DESCUENTO MEDICIÓN AUDIOMETRÍA GRATIS.\n",
      "\tSERVICIOS PSICOLOGÍA, NUTRICIÓN Y AUDIOLOGÍA 20 % DE DESCUENTO\n",
      "BENEFICIARIOS:",
      "PERSONAL MILITAR EN ACTIVIDAD, RETIRO Y FAMILIARES DIRECTOS EMPLEADOS CIVILES  Y FAMILIARES DIRECTOS",
    ],
  },
  {
    image: ImgRenzoCosta,
    title: "RENZO COSTA",
    benefits: [
      "\t10% TIENDAS PROPIAS (MIRAFLORES, SAN ISIDRO, OUTLET FÀBRICA Y TACNA).\n",
      "\t5% DESCUENTO EN LOS CENTROS COMERCIALES.\n",
      "BENEFICIARIOS:",
      "PERSONAL MILITAR EN ACTIVIDAD, RETIRO Y FAMILIARES DIRECTOS EMPLEADOS CIVILES  Y FAMILIARES DIRECTOS",
    ],
  },
  {
    image: ImgLazzosComerciales,
    title: "LAZZOS COMERCIALES",
    benefits: [
      "\t20% DE DESCUENTO SOBRE EL PRECIO DE ETIQUETA EN TODAS LAS TIENDAS MOSSA SHOES Y VISANO TIENDA FÍSICO Y VIRTUAL\n",
      "BENEFICIARIOS:",
      "PERSONAL MILITAR EN ACTIVIDAD, RETIRO Y FAMILIARES DIRECTOS EMPLEADOS CIVILES  Y FAMILIARES DIRECTOS",
    ],
  },
  {
    image: ImgMultident,
    title: "MULTIDENT",
    benefits: [
      "\tCOSTOS DIFERENCIADOS DE LA TARIFA REGULAR, SEGÚN TARIFARIO",
      "BENEFICIARIOS:",
      "PERSONAL MILITAR EN ACTIVIDAD, RETIRO Y FAMILIARES DIRECTOS EMPLEADOS CIVILES  Y FAMILIARES DIRECTOS",
    ],
  },
  {
    image: ImgMovilBus,
    title: "Movil Bus",
    benefits: [
      "SERVICIO DE PASAJERO TODO EL AÑO 20% DE DESCUENTO.\n",
      "SERVICIO TRANSPORTE DE CORRESPONDENCIA, PAQUETERÍA, ENCOMIENDAS, CARGA LIGERA O MEDIANA. \n",
      "30% DE DESCUENTO DE PROVINCIA A LIMA.\n",
      " 20 % DE LIMA A PROVINCIA\n",
      "PERSONAL MILITAR EN ACTIVIDAD, RETIRO Y FAMILIARES DIRECTOS EMPLEADOS CIVILES  Y FAMILIARES DIRECTOS",
    ],
  },
  {
    image: ImgSmartFit,
    title: "Smart Fit",
    benefits: [
      "EXONERACIÓN DEL PAGO ÚNICO DE “MATRÍCULA”.\n",
      "EXONERACIÓN DEL PAGO ANUAL DE “MANTENIMIENTO”.",
      "EXONERACIÓN DEL PAGO POR PENALIDAD\n",
      "ENTRENAMIENTO EN TODO EL PERÚ Y LATINOAMÉRICA.",
      "INVITACIÓN DE AMIGOS Y FAMILIARES HASTA 5 VECES AL MES.n",
      "PAGO MENSUAL S/ 99.\n",
      "INGRESANDO CON EL CÓDIGO DE VALIDACIÓN “CORPORATIVO EP”\n",
      "BENEFICIARIOS:",
      "PERSONAL MILITAR EN ACTIVIDAD, RETIRO Y FAMILIARES DIRECTOS EMPLEADOS CIVILES  Y FAMILIARES DIRECTOS",
    ],
  },
  {
    image: ImgApelac,
    title: "Apelac",
    benefits: [
      "\tCOSTOS DIFERENCIADOS DE LA TARIFA REGULAR, SEGÚN TARIFARIO",
      "BENEFICIARIOS:",
      "PERSONAL MILITAR EN ACTIVIDAD, RETIRO Y FAMILIARES DIRECTOS EMPLEADOS CIVILES  Y FAMILIARES DIRECTOS",
    ],
  },
  {
    image: ImgLogistas,
    title: "Logistas",
    benefits: [
      "•\tSERVICIOS DE MANTENIMIENTO VEHICULAR CORRECTIVOS\n",
      "COSTOS DIFERENCIADOS DE LA TARIFA REGULAR, SEGÚN TARIFARIO",
      "BENEFICIARIOS:",
      "PERSONAL MILITAR EN ACTIVIDAD, RETIRO Y FAMILIARES DIRECTOS EMPLEADOS CIVILES  Y FAMILIARES DIRECTOS",
    ],
  },
  {
    image: ImgSugo,
    title: "Sugo",
    benefits: [
      "ACCESO EN LÍNEA EN SUS PLATAFORMAS EN COMPRAS DE CONSUMO SOSTENIBLE\n" +
        "HASTA 50% DEL PRECIO EN EL MERCADO\n",
      "BENEFICIARIOS:",
      "PERSONAL MILITAR EN ACTIVIDAD, RETIRO Y FAMILIARES DIRECTOS EMPLEADOS CIVILES  Y FAMILIARES DIRECTOS",
    ],
  },
];
