import {
  ImgBthHotelRebelTacna,
  ImgCentroOpticoJesus,
  ImgMirandaEscobarPeruTravels,
  ImgPacificSuitesHotel,
} from "../images";

export const conventionProvincies = [
  {
    province: "piura-sullana",
    type: "hotel",
    title: 'HOTEL "LA SIESTA"',
    benefits: [
      "10% DE DESCUENTO CON LA PRESENTACIÓN DE SU CIP",
      "ALCANCE:",
      "SOLO EN ALOJAMIENTO (HABITACIONES).",
      " METODOS DE PAGO: EFECTIVO, YAPE, PLIM O TRANSFERENCIAS.",
      " PRESENTACIÓN DE CIP/CIF EN ACTIVIDAD Y/O RETIRO",
      "REQUISITOS:",
      "PERSONAL MILITAR, SERVIDORES PUBLICOS  DEL EJÉRCITO Y FAMILIA MILITAR",
    ],
  },
  {
    province: "tacna",
    type: "hotel",
    title: "EL HOTEL MAXIMO'S",
    benefits: [
      "20% DE DESCUENTO CON LA PRESENTACIÓN DE SU CIP",
      "ALCANCE:",
      "BRINDARA HOSPEDAJE, DE LA LISTA DE PRECIOS VIGENTES A LA FECHA, EN QUE SEAN SOLICITADOS LOS SERVICIOS, INCLUYE DESAYUNO BUFFET DE CORTESÍA.",
      "REQUISITOS:",
      "PERSONAL MILITAR Y CIVIL EN SITUACIÓN DE ACTIVIDAD Y RETIRO, ASI COMO PERSONAL MILITAR DEL PAÍS DE CHILE, QUE VISITAN LA CIUDAD DE TACNA, EN VISITAS ",
    ],
  },
  {
    province: "tacna",
    type: "hotel",
    title: "DM HOTEL",
    benefits: [
      "TARIFAS PREFERENCIALES",
      "ALCANCE:",
      "REQUISITOS:",
      "BRINDARA DESCUENTOS EN TODAS SUS HABITACIONES, INCLUYE DESAYUNO BUFFET:",
      "HABITACION ESTÁNDAR INDIVIDUAL $ 55.00",
      "HABITACIÓN ESTÁNDAR MATRIMONIAL $65.00",
      "HABITACIÓN ESTÁNDAR DOBLE $ 75.OO",
      "PERSONAL MILITAR Y CIVIL EN SITUACIÓN DE ACTIVIDAD Y RETIRO, ASI COMO PERSONAL MILITAR DEL PAÍS DE CHILE, QUE VISITAN LA CIUDAD DE TACNA, EN VISITAS ",
    ],
  },
  {
    province: "tacna",
    type: "hotel",
    title: "PACIFIC SUITES HOTEL",
    benefits: [
      "ALCANCE DEL CONVENIO:",
      "Personal militar y civil en situación de actividad y retiro Personal militar del país de Chile, que visitan la ciudad de Tacna, en visitas protocolares y personales.",
      "BENEFICIO:",
      "Brindará el servicio de hospedaje, con un descuento del:",
      "- 20% de la lista de precios vigentes a la fecha, para pago en efectivo.",
      "- 15% de descuento para pago con tarjeta de crédito.",
      "- Incluye desayuno buffet de cortesía",
    ],
  },
  {
    province: "tacna",
    type: "hotel",
    title: "BTH HOTEL REBEL TACNA",
    benefits: [
      "ALCANCE DEL CONVENIO:",
      "Personal militar y civil en situación de actividad y retiro Personal militar del país de Chile, que visitan la ciudad de Tacna, en visitas protocolares y personales.",
      "BENEFICIO:",
      "-\tTarifas incluyen impuestos (10% servicios / 18% IGV).",
      "-\tTarifa incluye desayuno de 7:00 am. a 10:00 am.",
      "-\tCheck in 15:00 hrs / Check out: 12:00 hrs.",
      "-\tEstacionamientos sujetos a disponibilidad.",
      "TARIFAS EXCLUSIVAS SOLO PARA PERSONAL DE LA FFAA:",
      "- 20% de descuento en NOMAD y MADBAR.",
      "- Early check in y late check out free (sujeto a disponibilidad del hotel)",
      "- 30% de descuento en alquiler de salones de eventos y sala de cine",
      "- 1 salón de cortesía una vez al mes GRATIS (solicitado por algún alto mando).",
    ],
  },
  {
    province: "piura-sullana",
    type: "restaurant",
    title: "D' PALETAS",
    benefits: [
      "10% DE DESCUENTO CON LA PRESENTACIÓN DE SU CIP",
      "ALCANCE:",
      "CONSUMOS MINIMOS DE S/. 25 EN TODAS NUESTRA CARTAS.",
      "EL DESCUENTO SE APLICA DE LUNES A VIERNES.",
      "NO SE APLICA NI LOS DIAS SÁBADOS, DOMINGOS Y FERIADOS.",
      "MÉTODOS DE PAGO: EFECTIVO, YAPE, PLIM O TRANSFERENCIA.",
      "PRESENTACIÓN DE CIP/CIF EN ACTIVIDAD Y/O RETIRO.",
      "REQUISITOS:",
      "PERSONAL MILITAR, SERVIDORES PUBLICOS  DEL EJÉRCITO Y FAMILIA MILITAR",
    ],
  },
  {
    province: "piura-sullana",
    type: "restaurant",
    title: "DON LIMÓN",
    benefits: [
      "10% DE DESCUENTO CON LA PRESENTACIÓN DE SU CIP",
      "ALCANCE:",
      "SOLO EN COMIDA POR EL CONSUMO MÍNIMO POR EL COMSUMO MÍNIMO DE S/. 100.00.",
      "MÉTODOS DE PAGO: EFECTIVO, YAPE, PLIM, O TRANSFERENCIAS.",
      "PRESENTACIÓN DE CIP/CIF EN ACTIVIDAD Y/O RETIRO",
      "REQUISITOS:",
      "PERSONAL MILITAR, SERVIDORES PUBLICOS  DEL EJÉRCITO Y FAMILIA MILITAR",
    ],
  },
  {
    province: "piura-sullana",
    type: "restaurant",
    title: "SAINT ROSE",
    benefits: [
      "10% DE DESCUENTO CON LA PRESENTACIÓN DE SU CIP",
      "ALCANCE:",
      "SOLO EN COMIDA POR EL CONSUMO MÍNIMO POR EL COMSUMO MÍNIMO DE S/. 100.00.",
      "MÉTODOS DE PAGO: EFECTIVO, YAPE, PLIM, O TRANSFERENCIAS.",
      "PRESENTACIÓN DE CIP/CIF EN ACTIVIDAD Y/O RETIRO",
      "REQUISITOS:",
      "PERSONAL MILITAR, SERVIDORES PUBLICOS  DEL EJÉRCITO Y FAMILIA MILITAR",
    ],
  },
  {
    province: "piura-sullana",
    type: "restaurant",
    title: 'CHIFA RESTAURANTE "WONG SEN"',
    benefits: [
      "10% DE DESCUENTO CON LA PRESENTACIÓN DE SU CIP",
      "ALCANCE:",
      "DESCUENTO EN CONSUMO DE COMIDA Y TODO TIPO DE BEBIDAS, POR EL CONSUMO MINIMO DE S/. 50.00.",
      "MÉTODOS DE PAGO: EFECTIVO, YAPE, PLIM O TRANSFERENCIAS.",
      "PRESENTACIÓN DE CIP/CIF EN ACTIVIDADES Y/O RETIRO.",
      "REQUISITOS:",
      "PERSONAL MILITAR, SERVIDORES PUBLICOS  DEL EJÉRCITO Y FAMILIA MILITAR",
    ],
  },
  {
    province: "tacna",
    type: "restaurant",
    title: 'PARQUE GASTRONOMICO "DON MAXIMO"',
    benefits: [
      "10% DE DESCUENTO CON LA PRESENTACIÓN DE SU CIP",
      "ALCANCE:",
      "BRINDARA ATENCIÓN CON UNA VARIADA GASTRONOMÍA Y DE CALIDAD EN LA PREPARACIÓN DE SUS ALIMENTOS Y BEBIDAS, EN TODO SU STAND",
      "REQUISITOS:",
      "PERSONAL MILITAR Y CIVIL EN SITUACIÓN DE ACTIVIDAD Y RETIRO, ASI COMO PERSONAL MILITAR DEL PAÍS DE CHILE, QUE VISITAN LA CIUDAD DE TACNA, EN VISITAS ",
    ],
  },
  {
    province: "tacna",
    type: "restaurant",
    title: "RESTAURANTE DA PASTA E.I.R.L.",
    benefits: [
      "ALCANCE:",
      "Personal militar y civil en situación de actividad y retiro, así como para sus familiares directos, debidamente identificados con su carnet de identidad.",
      "Personal militar del país de Chile, que visitan la ciudad de Tacna, en visitas protocolares y personales, debidamente acreditados.",
      "BENEFICIOS:",
      "Servicio de atención los días lunes, martes, miércoles y jueves de todo el año con un 10% de descuento en toda la carta de comida.  (Gastronomía de comida italiana, comida criolla, comida china,  así como comida con productos hidrobiológicos, etc.).",
      "Descorcho libre al mes para que disfrutar del vino que  se prefiera y  en el día del cumpleaños del BENEFICIARIO le otorgará un postre libre a elegir.",
    ],
  },
  {
    province: "tacna",
    type: "restaurant",
    title: "RESTAURANTE FUEGOS PERUANOS MAZ TURISMO INTEGRAL S.A.C.",
    benefits: [
      "ALCANCE:",
      "Personal militar en situación de actividad o retiro, al personal civil así como a sus familiares; asimismo, al personal militar del Ejército de Chile,  debidamente acreditados.",
      "BENEFICIOS:",
      "Servicio de atención con una variada gastronomía, con un descuento del 30%, en todo consumo.",
    ],
  },
  {
    province: "tacna",
    type: "restaurant",
    title: 'RESTAURANTE "TRADICIONES PERUANAS" S.R.L.',
    benefits: [
      "ALCANCE:",
      "Personal militar y civil en situación de actividad y retiro, así como para sus familiares directos, debidamente identificados con su carnet de identidad.",
      "BENEFICIOS:",
      "Se otorgará el descuento del 10% para pedidos a la carta de comida criolla, parrillas y cocktails. El pago será en efectivo.",
    ],
  },
  {
    province: "tacna",
    type: "studies",
    title: 'UNIVERSIDAD "ALAS PERUANAS" - FILIAL TACNA',
    benefits: [
      "ALCANCE:",
      "Personal de Oficiales, Supervisores, Técnicos, Sub Oficiales y Personal de Tropa SMV.",
      "BENEFICIOS:",
      "Establece acuerdos para desarrollar actividades de formación de Pregrado (estomatología, sicología y medicina física), con la finalidad de mejorar la calidad de vida y el nivel de la salud del personal, mediante un programa de prácticas  profesionales para los alumnos de la UAP, en los Cuarteles de Tarapacá, Albarracín, Palca y Miculla de la 3a Brigada de Caballería, lugares donde la UAP-Tacna, participará con sus respectivas carreras profesionales de salud; las cuales también servirán como sede de docencia asistencial, dentro del marco normativo vigente.",
    ],
  },
  {
    province: "tacna",
    type: "studies",
    title: "UNIVERSIDAD PRIVADA DE TACNA",
    benefits: [
      "ALCANCE:",
      'Personal de la 3a Brigada de Caballería "Tacna".',
      "BENEFICIOS:",
      "Coordinar, concertar y ejecutar programas de apoyo recíproco entre ambas instituciones en las áreas académicas, docencia, asistencial y otros de interés común.",
    ],
  },
  {
    province: "tacna",
    type: "studies",
    title: "ESCUELA DE GASTRONOMIA, ADMINISTRACIÓN Y TURISMO (EGATUR)",
    benefits: [
      "ALCANCE:",
      "Personal militar y civil en actividad y situación de retiro, así como para sus familiares directos.",
      "BENEFICIOS:",
      "- Brinda el 50% de descuento en las carreras que ofrecen.",
      "- Otorga tres (03) becas integrales.",
    ],
  },
  {
    province: "tacna",
    type: "studies",
    title: 'I.E.P "DAYPER PERÚ" E.I.R.L.',
    benefits: [
      "ALCANCE:",
      "Personal militar y civil en actividad y situación de retiro, así como para sus familiares directos.",
      "BENEFICIOS:",
      "- Brinda el 60% de descuento de matrícula y pensión en todas las carreras técnicas que ofrece.",
      "- Otorga 50 (cincuenta) becas semi-integrales de   estudio (BSIE) cada semestre.",
    ],
  },
  {
    province: "tacna",
    type: "studies",
    title:
      "DIRECCIÓN REGIONAL DE EDUCACIÓN TACNA Y LA UNIDAD DE GESTIÓN EDUCATIVA LOCAL DE TACNA",
    benefits: [
      "ALCANCE:",
      "El presente Convenio tiene por objeto establecer los lineamientos específicos de mutua cooperación que permitan generar oportunidades y resultados educativos de calidad al personal de Tropa que estudia en el CEBA “JOSÉ JOAQUÍN INCLÁN” en Educación Básica Alternativa. Se ha suscrito una Adenda para prolongar un año más el convenio.",
      "BENEFICIOS:",
      'Personal de Tropa Servicio Militar Voluntario de la 3a Brigada de Caballería "Tacna".',
    ],
  },
  {
    province: "puno",
    type: "health",
    title: 'CLINICA "SAUCES MEDICAL CENTER"',
    benefits: [
      "10% DE DESCUENTO CON LA PRESENTACIÓN DE SU CIP",
      "ALCANCE:",
      "COSTOS DIFERENCIADOS",
      "REQUISITOS",
      "PERSONAL MILITAR (INCLUYE PERSONAL DE TROPA), SERVIDORES PÚBLICOS  DEL EJÉRCITO Y FAMILIA MILITAR",
    ],
  },
  {
    province: "tacna",
    type: "health",
    title: "MB REHAB FISOTERAPIA REA BILITACIÓN Y SALUD S.A.C.",
    benefits: [
      "TARIFAS PREFERENCIAL EN EVALUACION FISIOTETERAPÉUTICA Y REHABILITACIÓN",
      "ALCANCE:",
      "REALIZA SERVICIOS EN FISIOTERAPIA Y REHABILITACIÓN  FISICA, BRINDANDO TRATAMIENTOS CONTRA DIVERSOS TIPOS DE DOLORES, DISFUNCIONES, LESIONES TRAUMATOLÓGICAS, NEUROLÓGICAS, DEPORTIVA  Y OTRAS , DE ACUERDO A UNA TARIFA PREFERENCIAL, OTORGANDO DESCUENTOS DEL 20% Y 30%",
      "REQUISITOS",
      "PERSONAL DE OFICIALES, TÉCNICOS, SUBOFICIALES, CLASES, SOLDADOS, PERSONAL CIVIL Y FAMILIARES DIRECTOS",
    ],
  },
  {
    province: "tacna",
    title: 'CENTRO ÓPTICO "JESÚS" E.I.R.L.',
    type: "health",
    benefits: [
      "ALCANCE:",
      "Personal militar en situación de actividad o retiro, al personal civil así como a sus familiares; asimismo, al personal militar del Ejército de Chile,  debidamente acreditados.",
      "BENEFICIOS:",
      "Servicio de atención con los descuentos diferenciales que a continuación se indican:",
      "PRODUCTO = PRECIO CON DESCUENTO DESDE S/.",
      "LenteS Antireflejo Filtro UV = S/ 49.90",
      "Lentes Antireflejo Filtro Azul y Filtro UV = S/ 69.90",
      "Lentes Fotocromático Filtro UV = S/ 89.90",
      "Gafas de Sol Optico = S/ 59.90",
      "Bifocales Blanco UV = S/ 89.90",
      "Bifocales Antireflejo Filtro UV = S/ 99.90",
      "Bifocales Fotocromático Filtro UV = S/ 149.90",
      "Multifocal Blanco Filtro UV = S/ 139.90",
      "Multifocal Antireflejo Filtro UV = S/ 150.00",
      "SEGUNDO PAR DE LENTES = 50% de descuento",
    ],
  },
  {
    province: "tacna",
    type: "transport",
    title: "AGENCIA DE VIAJES MIRANDA Y ESCOBAR PERÚ TRAVELS S.A.C.",
    benefits: [
      "ALCANCE DEL CONVENIO",
      "Personal de Oficiales, Supervisores, Técnicos, Sub Oficiales, Personal de Tropa Servicio Militar Obligatorio y Personal Civil, en actividad y en retiro así como para sus familiares directos.",
      "BENEFICIO",
      "Pago del servicio en dos (02) partes, el 50% del total deberá ser cancelado al momento de la emisión del servicio y el 50% restante en un plazo de treinta (30) días, en los servicios que se indica:",
      "- Emisión de boletos terrestres.",
      "- Emisión de boletos aéreos.",
      "- Emisión de programas turísticos locales, nacionales e internaciones.",
      "- En el caso de programas locales, nacionales e internacionales, tendrán la misma facilidad de pago pero deberán solicitar dichos servicios como mínimo 2 meses de anticipación y deberá ser pagado en su totalidad antes de la fecha de inicio del viaje.",
    ],
  },
  {
    province: "arequipa",
    type: "cake-shop",
    title: "PASTELERIA MOCCA",
    benefits: [
      "15% DE DESCUENTO CON LA PRESENTACIÓN DE SU CIP",
      "ALCANCE:",
      "DESCUENTOS EN LA ADQUISICION DE PRODUCTOS DE PASTELERIA.",
      "REQUISITOS",
      "PERSONAL MILITAR Y CIVIL EN SITUACION DE ACTIVIDAD Y RETIRO Y FAMILIARES DIRECTOS",
    ],
  },
  {
    province: "arequipa",
    type: "health",
    title: "ASOCIACION PSICOLOGICA UMANOS",
    benefits: [
      "50% DE DESCUENTO CON LA PRESENTACIÓN DE SU CIP",
      "ALCANCE:",
      "DESCUENTO EN CONSULTAS PSICOLÓGICAS Y TERAPIAS.",
      "REQUISITOS",
      "PERSONAL MILITAR Y CIVIL EN SITUACION DE ACTIVIDAD Y RETIRO Y FAMILIARES DIRECTOS",
    ],
  },
  {
    province: "arequipa",
    type: "health",
    title: "CENTRO PSICOLÓGICO PSICOUNE",
    benefits: [
      "50% DE DESCUENTO CON LA PRESENTACIÓN DE SU CIP",
      "ALCANCE:",
      "DESCUENTO EN CONSULTAS PSICOLÓGICAS Y 40 % DE DESCUENTOS EN TERAPIAS.",
      "REQUISITOS",
      "PERSONAL MILITAR Y CIVIL EN SITUACION DE ACTIVIDAD Y RETIRO Y FAMILIARES DIRECTOS",
    ],
  },
  {
    province: "ayacucho",
    type: "hotel",
    title: "HOTEL ALTIPACHA",
    benefits: [
      "60% DE DESCUENTO CON LA PRESENTACIÓN DE SU CIP",
      "ALCANCE:",
      "SOLO EN ALOJAMIENTO (HABITACIONES).    ",
      "REQUISITOS",
      "PERSONAL MILITAR Y FAMILIARES DIRECTOS",
    ],
  },
  {
    province: "chiclayo",
    type: "company",
    title: "EMPRESA AGROINDUSTRIAL HFE. BERRIES PERÚ",
    benefits: [
      "DESCUENTOS PREFERENCIALES",
      "DESARROLLAR TALLERES DE EMPLEABILIDAD QUE LOGREN LA INSERCIÓN LABORAL DEL PERSONAL DE TROPA PRÓXIMO A LICENCIARSE.",
      "OBTENIENDO DE ESTA MANERA QUE NUESTRO PERSONAL ADQUIERA COMPETENCIAS ACORDE AL PERFIL DEL MERCADO LABORAL (DE FORMA GRATUITO)",
      "REQUISITOS",
      "PERSONAL DE TROPA SMV",
    ],
  },
  {
    province: "chiclayo",
    type: "hotel",
    title: 'HOTEL & CASINO" WIN MEIER"',
    benefits: [
      "45%",
      "DESCUENTO EN TARIFAS DE HABITACIÓN EN TODAS LAS TARIFAS INCLUYEN TRASLADO AEROPUERTO-HOTEL, DESAYUNO EN EL RESTAURANTE DEL HOTEL, INTERNET INALÁMBRICO, ESTACIONAMIENTO GRATUITO, ACCESO LIBRE AL BUSINESS CENTER, USO DE PISCINA, ROOM SERVICE (10:30am - 11:00 pm), LAVANDERÍA Y PLANCHADO PREVIA SOLICITUD",
      "REQUISITOS",
      "OFICIALES, TECNICOS Y SUBOFICIALES, EMPLEADOS CIVILES",
    ],
  },
  {
    province: "chiclayo",
    type: "health",
    title: "ASOCIADOS EN SALUD S.A.C.",
    benefits: [
      "DESCUENTOS PREFERENCIALES",
      "20% DE DESCUENTO EN CONSULTA MÉDICA.BRINDAR SERVICIOS DE CONSULTA MÉDICA EN LAS ESPECIALIDADES DE CIRUGÍA GENERAL EN LAS ESPECIALIDADES DE CIRUGÍA GENERAL, CARDIOVASCULAR, GINECOLOGÍA, MEDICINA GENERAL, MEDICINA INTERNA, MEDICINA ESTÉTICA, NEUROLOGÍA, NEUROPEDIATRIA, NEUROCIRUGIA, OFTALMOLOGIA, OTORRINOLOGÍA, ODONTOLOGÍA, PEDIATRÍA, PSICOLOGÍA, REUMATOLOGÍA, TRAUMATOLOGÍA,TERAPIA FISICA Y REHABILITACIÓN\n",
      "20% DE DESCUENTOS EN TARIFAS VIGENTES DE ANATOMÍA PATOLÓGICA, CÁMARA HIPERBÁRICA, DENSITOMETRÍA ÓSEA, ECOGRAFÍA, LABORATORIO CLÍNICO, RAYOS X, TOMOGRAFÍA, TERAPIA FÍSICA Y REHABILITACIÓN.",
      "REQUISITOS",
      "PERSONAL MILITAR Y CIVIL EN SITUACIÓN DE ACTIVIDAD Y RETIRO",
    ],
  },
  {
    province: "chiclayo",
    type: "health",
    title: "HOSPITAL BELÉN",
    benefits: [
      "DESCUENTOS PREFERENCIALES",
      "ALCANCE",
      "40% DE DESCUENTO PARA EL PERSONAL DE OFICIALES.\n",
      "50% DE DESCUENTO PARA EL PERSONAL DE TECNICOS Y SUBOFICIALES Y SUS FAMILIARES, EMPLEADOS CIVILES,FAMIIARES Y PERSONAL MILITAR EN SITUACION DE RETIRO.\n",
      "FACILIDADES DE PAGO EN FARMACIA EN INTERVENCIONES QUIRURGICAS DE EMERGENCIA.\n",
      "EXONERACION DE PAGOS EN INTERVENCIONES QUIRÚRGICAS DE EMERGENCIA AL PERSONAL DE TROPA SERVICIO MILITAR\n",
      "35% EN ANALISIS DE LABORATORIO.\n",
      "ATENCIÓN DE PACIENTES EN TRABAJOS DE PARTOS DISTÓCICOS.\n",
      "ATENCIÓN PEDIATRICA A LOS HIJOS DE PERSONAL MILITAR Y CIVIL",
      "REQUISITOS:",
      "PERSONAL DE OFICIALES, TECNICOS Y SUB OFICIALES, PERSONAL DE TROPA SMV, PERSONAL CIVIL Y FAMILIARES DIRECTOS DEBIDAMENTE IDENTIFICADOS CON SU CARNET DE IDENTIDAD",
    ],
  },
  {
    province: "huancayo",
    type: "health",
    title: 'CENTRO DE TERAPIA "INFFEL"',
    benefits: [
      "ALCANCE:",
      "SE LE OTORGARA UN DESCUENTO EN CUALQUIERA DE LAS TERAPIAS.",
      "REQUISITOS",
      "PERSONAL MILITAR, CIVIL Y FAMILIARES ",
    ],
  },
  {
    province: "piura-sullana",
    type: "restaurant",
    title: "CHIFA SAN ZI",
    benefits: [
      "DESCUENTOS PREFERENCIALES",
      "ALCANCE:",
      "SE ENCUENTRA UBICADA EN MZ P1 LOTE 19 URBANIZACION JARDÍN 1RA ETAPA",
      "REQUISITOS",
      "PERSONAL MILITAR, SERVIDORES PÚBLICOS  DEL EJÉRCITO Y FAMILIA MILITAR",
    ],
  },
  // {
  //   province: "piura-sullana",
  //   type: "restaurant",
  //   title: '"DON LIMÓN"',
  //   benefits: [
  //     "ALCANCE:",
  //     "SOLO EN COMIDA POR EL CONSUMO MÍNIMO POR EL COMSUMO MÍNIMO DE S/. 100.00.\n",
  //     "MÉTODOS DE PAGO: EFECTIVO, YAPE, PLIM, O TRANSFERENCIAS.\n",
  //     "PRESENTACIÓN DE CIP/CIF EN ACTIVIDAD Y/O RETIRO  \n",
  //     "SE ENCUENTRA UBICADO EN LA CARRETERA PANAMERICANA NORTE 1.0 KM. PROVINCIA DE SULLANA DEPARTAMENTO DE PIURA",
  //     "BENEFICIOS",
  //     "PERSONAL MILITAR, SERVIDORES PÚBLICOS  DEL EJÉRCITO Y FAMILIA MILITAR",
  //   ],
  // },
  {
    province: "piura-sullana",
    type: "restaurant",
    title: "RESTAURANT EL LEÑADOR Y ALGO MAS",
    benefits: [
      "DESCUENTOS PREFERENCIALES",
      "ALCANCE:",
      "SE ENCUENTRA UBICADA EN LA CALLE SANTA CLARA N°340 URB SANTA ROSA",
      "REQUISITOS:",
      "PERSONAL MILITAR, SERVIDORES PÚBLICOS  DEL EJÉRCITO Y FAMILIA MILITAR",
    ],
  },
  {
    province: "piura-sullana",
    type: "restaurant",
    title: "MAYU COMIDA Y SALÓN",
    benefits: [
      "DESCUENTOS PREFERENCIALES",
      "ALCANCE:",
      "SE ENCUENTRA UBICADA EN LA CALLE SAN JUAN BOSCO N° 380",
      "REQUISITOS:",
      "PERSONAL MILITAR, SERVIDORES PÚBLICOS  DEL EJÉRCITO Y FAMILIA MILITAR",
    ],
  },
  // {
  //   province: "piura-sullana",
  //   type: "restaurant",
  //   title: "SAINT ROSE",
  //   benefits: [
  //     "DESCUENTOS PREFERENCIALES",
  //     "ALCANCE:",
  //     "SOLO EN COMIDA POR EL CONSUMO MÍNIMO POR EL COMSUMO MÍNIMO DE S/. 100.00.\n",
  //     "MÉTODOS DE PAGO: EFECTIVO, YAPE, PLIM, O TRANSFERENCIAS.\n",
  //     "PRESENTACIÓN DE CIP/CIF EN ACTIVIDAD Y/O RETIRO.\n",
  //     "SE ENCUENTRA UBICADO EN LA CALLE SANTA CLARA N°601 URBANIZACION SANTA ROSARA",
  //     "REQUISITOS:",
  //     "PERSONAL MILITAR, SERVIDORES PÚBLICOS  DEL EJÉRCITO Y FAMILIA MILITAR",
  //   ],
  // },
  {
    province: "trujillo",
    type: "hotel",
    title: 'HOTEL "COLONIAL"',
    benefits: [
      "28%",
      "ALCANCE:",
      "DESCUENTO SOLO EN ALOJAMIENTO (HABITACIONES)",
      "METODOS DE PAGO: EFECTIVO, YAPE, PLIM O TRANSFERENCIAS",
      "PRESENTAR CIP/CIF EN ACTIVIDAD Y/O RETIRO.",
      "REQUISITOS:",
      "PERSONAL MILITAR, SERVIDORES PUBLICOS DEL EJÉRCITO Y FAMILIA MILITAR",
    ],
  },
  {
    province: "trujillo",
    type: "hotel",
    title: 'HOTEL "EL BRUJO"',
    benefits: [
      "10%",
      "ALCANCE:",
      "DESCUENTO SOLO EN ALOJAMIENTO (HABITACIONES)",
      "METODOS DE PAGO: EFECTIVO, YAPE, PLIM O TRANSFERENCIAS",
      "PRESENTAR CIP/CIF EN ACTIVIDAD Y/O RETIRO.",
      "REQUISITOS:",
      "PERSONAL MILITAR, SERVIDORES PUBLICOS DEL EJÉRCITO Y FAMILIA MILITAR",
    ],
  },
  {
    province: "trujillo",
    type: "hotel",
    title: 'HOTEL "RADO"',
    benefits: [
      "10%",
      "ALCANCE:",
      "DESCUENTO SOLO EN ALOJAMIENTO (HABITACIONES)",
      "METODOS DE PAGO: EFECTIVO, YAPE, PLIM O TRANSFERENCIAS",
      "PRESENTAR CIP/CIF EN ACTIVIDAD Y/O RETIRO.",
      "REQUISITOS:",
      "PERSONAL MILITAR, SERVIDORES PUBLICOS DEL EJÉRCITO Y FAMILIA MILITAR",
    ],
  },
  {
    province: "trujillo",
    type: "restaurant",
    title: "DANIELITA CEVICHERÍA RESTAURANTE",
    benefits: [
      "15%",
      "ALCANCE:",
      "DESCUENTO EN TODA NUESTRA CARTA",
      "DESCUENTO SE APLICA TODOS LOS DIAS.",
      "METODOS DE PAGO: EFECTIVO, YAPE, PLIM O TRANSFERENCIAS.",
      "PRESENTAR CIP/CIF EN ACTIVIDAD Y/O RETIRO.",
      "REQUISITOS:",
      "PERSONAL MILITAR, SERVIDORES PUBLICOS DEL EJÉRCITO Y FAMILIA MILITAR",
    ],
  },
  {
    province: "tumbes",
    type: "hotel",
    title: "HOTEL ROMA",
    benefits: [
      "15%",
      "ALCANCE:",
      "DESCUENTOS EN TODOS SUS SERVICIOS",
      "UBICACIÓN: CALLE GRAU N° 425 PLAZA DE ARMAS DE TUMBES",
      "REQUISITOS:",
      "PERSONAL MILITAR EN ACTIVIDAD O RETIRO, EMPLEADOS CIVILES Y FAMILIARES DIRECTOS (PADRES DEL TITULAR, ESPOSA E HIJOS)",
    ],
  },
  {
    province: "tumbes",
    type: "hotel",
    title: "HOTEL RESTAURANTE LAS CABAÑAS DE ZORRITOS",
    benefits: [
      "10%",
      "ALCANCE:",
      "DESCUENTO EN PLATOS  A LA CARTA",
      "DESCUENTO EN HABITACIONES.",
      "SE ENCUENTRA UBICADO EN LA AV PANAMERICANA NORTE KM 214.50 BOCAPAN CONTRAALMIRANTE VILLAR ZORRITOS TUMBES",
      "REQUISITOS:",
      "PERSONAL MILITAR EN ACTIVIDAD O RETIRO, PERSONAL CIVIL EN ACTIVIDAD O CESANTE, FAMILIARES DIRECTOS, ESPOSA, HIJOS Y PADRES",
    ],
  },
  {
    province: "tumbes",
    type: "restaurant",
    title: "EL HUERTO DEL SABER",
    benefits: [
      "10%",
      "ALCANCE:",
      "*DESCUENTO EN PLATOS  A LA CARTA PESCADOS, CARNES Y MARISCOS.",
      "SE ENCUENTRA UBICADO EN SAN JUAN DE LA VIRGEN- TUMBES",
      "REQUISITOS:",
      "PERSONAL MILITAR EN ACTIVIDAD O RETIRO, PERSONAL CIVIL EN ACTIVIDAD O CESANTE, FAMILIARES DIRECTOS, ESPOSA, HIJOS Y PADRES",
    ],
  },
  {
    province: "tumbes",
    type: "transport",
    title: "LA COLMENA TOURS",
    benefits: [
      'EMPRESA DE TRANSPORTE TURISTICO "LA COLMENA TOURS" EIRL',
      "20%",
      "ALCANCE:",
      "DESCUENTOS EN TODOS SUS SERVICIOS",
      "REQUISITOS:",
      "PERSONAL MILITAR EN ACTIVIDAD O RETIRO, EMPLEADOS CIVILES Y FAMILIARES DIRECTOS (PADRES DEL TITULAR, ESPOSA E HIJOS)",
    ],
  },
  {
    province: "merced",
    type: "hotel",
    title: "LOS COCOS",
    benefits: [
      'EMPRESA DE TRANSPORTE TURISTICO "LA COLMENA TOURS" EIRL',
      "15%",
      "ALCANCE:",
      "ACCESO A DESCUENTOS EN HABITACIONES",
      "SE ENCUENTRA UBICADO:",
      "Av. Principal S/N, San Ramón 12840",
      "TELEFONO: (064) 333458",
      "REQUISITOS:",
      "PERSONAL MILITAR, CIVIL  Y FAMILIARES DIRECTOS (CÓNYUGE E HIJOS) EN ACTIVIDAD Y RETIRO",
    ],
  },
  {
    province: "merced",
    type: "center-playtime",
    title: "LAS TUTUNAS",
    benefits: [
      "10%",
      "ALCANCE:",
      "ACCESO A DESCUENTOS EN USO DE SUS INSTALACIONES (PISCINA Y CAMPO DEPORTIVO",
      "SE ENCUENTRA UBICADO:",
      "Calle Las Guanábanas s/n Urb., Av. Manuel A. Pinto-La Merced",
      "TELEFONO: 942600089",
      "REQUISITOS:",
      "PERSONAL MILITAR, CIVIL  Y FAMILIARES DIRECTOS (CÓNYUGE E HIJOS) EN ACTIVIDAD Y RETIRO",
    ],
  },
  {
    province: "chiclayo",
    type: "clinic",
    title: "SANTA ANA SALUD",
    benefits: [
      "20%",
      "ALCANCE:",
      "BRINDA SERVICIO DE SALUD ESPECIALIZADA",
      "INCREMENTA SERVICIO DE SALUD ESPECIALIZADA, RESOLVIENDO DE INTEGRAL LOS PROBLEMAS DE SALUD.",
      "RESOLVIENDO DE INTEGRAL LOS PROBLEMAS DE SALUD.",
      "REQUISITOS:",
      "PERSONAL DE OFICIALES, TECNICOS Y SUB OFICIALES, PERSONAL DE TROPA SMV, PERSONAL CIVIL Y FAMILIARES DIRECTOS.",
    ],
  },
  {
    province: "lambayeque",
    type: "gym",
    title: "GIMNASIO WORLD LIGHT",
    benefits: [
      "DESCUENTOS PREFERENCIALES",
      "ALCANCE:",
      "OFRECE TRES (03) DÍAS DE PRUEBA PARA ACUDIR AL GIMNASIO WORLD LIGHT EN CUALQUIERA DE SUS SEDES.  ",
      "DESCUENTO CON EL 30% EN EL PAQUETE COMPLETO OBTENIENDO EL PRECIO DE S/. 90.00 EN LAMBAYEQUE. ",
      "DESCUENTO CON EL 20% OBTENIENDO EL PRECIO DE S/. 150.00 EN LAS SEDES DE CHICLAYO (SANTA VICTORIA, MATÍA IZAGA, SÁENZ PEÑA Y BOLGNESI). ",
      "AREA CARDIOVASCULAR.",
      "ÁREA DE MÁQUINAS.",
      "PROGRAMA DE ENTRANAMIENTO SEMI PERSONALIZADO.",
      "BAILE",
      "CYCLING",
      "CROSSFI",
      "ASESORÍA NUTRICIONAL PERSONALIZADA",
    ],
  },
];
