export { default as phoneCodes } from "./phoneCodes.json";
export * from "./limaInstitutes";
export * from "./provinceInstitutes";
export * from "./universities";
export * from "./institutes";
export * from "./pre-academies";
export * from "./companies";
export * from "./banks";
export * from "./requerimentsJace";
export * from "./campusCircleMilitary";
export * from "./campusTechniciansMilitary";
export * from "./conventionInternational";
