import {
  Autonomaica,
  Cayetano,
  Esan,
  ImgCatolicaSede,
  ImgCesarVallejo,
  ImgCientificaDelSur,
  ImgConservatorio,
  ImgFedericoVidarreal,
  ImgJaimeBausate,
  ImgMarcelinoChampagnat,
  ImgNorbertWiener,
  ImgRicardoPalma,
  ImgSanIngnacioLoyola,
  ImgSanJuanBautista,
  ImgSanMarcos,
  ImgSanMartin,
  ImgUcal,
  ImgUniAnahuaca,
  ImgUniAutonoma,
  ImgUniContinental,
  ImgUnife,
  ImgUniversidadDelPacifico,
  ImgUpc,
  ImgUtp,
  Newman,
  Norte,
  Unilima,
  Unir,
  Upal,
  Uprit,
} from "../images";
import { UniversityConventionPdf } from "../docs";
import { faPaste } from "@fortawesome/free-solid-svg-icons";

export const universities = [
  {
    image: ImgUpc,
    title: "UPC",
    benefits: [
      "PREGRADO: ",
      "50% de descuento en matricula – alumnos nuevos.",
      "25% primera cuota, alumnos nuevos.",
      "20% de descuento en las cuotas por ciclo académico (aplica a las 5 boletas.",
      "",
      "EPE ONLINE:",
      "20% de descuento en matricula – alumnos nuevos.",
      "25% primera cuota, alumnos nuevos.",
      "20% de descuento en las 4 cuotas por ciclo académico (aplica desde la 2 cuota hasta la 5ta sin retroactividad.)",
      "",
      "EPG ESCUELA DE POSGRADO):",
      "20%de descuento en las pensiones de enseñanza.",
      "Wetalk (programa de ingles) modalidad virtual regular intensiva.",
      "Descuento en las pensione de enseñanza.",
      "",
      "ALCANCE:",
      "Personal militar en actividad o retiro, personal civil en actividad y cesante, así como sus familiares directos (cónyuge, hijos y hermanos)",
      "- OO, SUP. TCOS. SSOO.  Tropa activo y Licenciado.",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [
      { url: "https://www.utp.edu.pe" },
      {
        url: "https://tramites.cobiene.com/",
        text: "Solicita tu convenio SITRACON",
        icon: faPaste,
      },
    ],
  },
  {
    image: ImgCientificaDelSur,
    title: "CIENTÍFICA DEL SUR",
    benefits: [
      "CENTRO DE IDIOMAS (CIDIO)",
      "15 % de descuento en el pago de las pensiones de inglés y portugués\n",
      "",
      "PREGRADO:",
      "40 % de descuento en pago de las pensiones en carreras de enfermería, obstetricia y medicina humana, sobre la escala E.",
      "60% de descuento en pago de las pensiones en las otras carreras, sobre la escala E.",
      "",
      "CARRERAS PARA LAS PERSONAS QUE TRABAJAN (CPE)",
      "30 %  de descuento en el pago de las pensiones, Administración de empresas, Ingeniería de sistemas, Derecho, Psicología, Comunicación y publicidad, Nutrición y dietética",
      "",
      "POSGRADO:",
      "10 % de descuento en maestría y especializaciones.",
      "",
      "FORMACIÓN CONTINUA",
      "30% descuento en el pago de las pensiones de los cursos",
      "",
      "ALCANCE:",
      "Personal militar en actividad o retiro, personal civil en actividad y cesante, así como sus familiares directos (cónyuge, hijos y hermanos)",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [
      { url: "https://www.cientifica.edu.pe" },
      {
        url: "https://tramites.cobiene.com/",
        text: "Solicita tu convenio SITRACON",
        icon: faPaste,
      },
    ],
  },

  {
    image: ImgCesarVallejo,
    title: "CESAR VALLEJO",
    benefits: [
      "PREGRADO:",
      "Categoría B: en pensiones para los ingresantes de pregrado regular en todas las carreras profesionales.",
      "Otorgar el 5% de descuento adicional del costo total de la pensión del semestre al momento de la matrícula, a los beneficiarios del presente convenio que se matriculen en todas las materias establecidas o por el pago total anticipada de la 'pensión.",
      "",
      "POSGRADO: ",
      "Categoría B: para los ingresantes de posgrado y para estudios de maestrías.",
      "Categoría C: en pensiones para los que ocupen el primer puesto del cuadro de méritos semestral.",
      "",
      "PROGRAMA FORMACIÓN ADULTOS:",
      "Categoría B en pensiones para el programa de formación de adultos.",
      "Categoría C: en el programa de formación para adultos que habiendo culminado en semestre académico anterior se ubique en el primer puesto del cómputo general.",
      "ALCANCE:",
      "Personal militar en situación de actividad y retiro, personal civil en actividad o cesantes, así como sus familiares directos (cónyuge , hijos, padres y hermanos en caso de ser trabajadores solteros)",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [
      { url: "https://www.ucv.edu.pe" },
      {
        url: "https://tramites.cobiene.com/",
        text: "Solicita tu convenio SITRACON",
        icon: faPaste,
      },
    ],
  },
  {
    image: ImgFedericoVidarreal,
    title: "FEDERICO VILLARREAL",
    benefits: [
      "PREGRADO:",
      "25 % de descuento en matrícula y pensiones en las diferentes  maestrías y doctorados",
      "",
      "ALCANCE:",
      "Personal militar en actividad o retiro, Personal civil en actividad y cesante así como a familiares directos (cónyuge, hijos y hermanos)\n",
      "- OO, SUP. TCOS. SSOO.  Tropa activo y Licenciado.",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [
      { url: "http://www.unfv.edu.pe" },
      {
        url: "https://tramites.cobiene.com/",
        text: "Solicita tu convenio SITRACON",
        icon: faPaste,
      },
    ],
  },
  {
    image: ImgJaimeBausate,
    title: "JAIME BAUSATE Y MEZA",
    benefits: [
      "PREGRADO:",
      "20 % de descuento sobre el costo de la pensión en las carreras de periodismo, escuela profesional de comunicación audiovisual, en cualquiera de sus modalidades.",
      "",
      "POSGRADO:",
      "20 % de descuento sobre el costo de la pensión en enseñanza de posgrado, diplomados y curso de proyección social, en cualquiera de sus modalidades.",
      "",
      "ALCANCE:",
      "Personal militar en actividad o retiro, personal civil en actividad o cesantes, así como a familiares directos (cónyuge, hijos y hermanos)\n",
      "- OO, SUP. TCOS. SSOO.  Tropa activo y Licenciado.",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [
      { url: "http://bausate.edu.pe" },
      {
        url: "https://tramites.cobiene.com/",
        text: "Solicita tu convenio SITRACON",
        icon: faPaste,
      },
    ],
  },
  {
    image: ImgMarcelinoChampagnat,
    title: "MARCELINO CHAMPAGNAT",
    benefits: [
      "PREGRADO: ",
      "20 % de descuento en el pago de las pensiones en las carreras de administración, psicología y contabilidad. Asimismoen diplomados y cursos de especialización",
      "",
      "POSGRADO:",
      "10% de descuento en el pago de las pensiones en maestría y doctorado. ",
      "",
      "ALCANCE:",
      "Personal militar en actividad o retiro, Personal civil en actividad y cesante así como a familiares directos (cónyuge, hijos y hermanos)\n",
      "- OO, SUP. TCOS. SSOO.  Tropa activo y Licenciado.",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [
      { url: "https://umch.edu.pe" },
      {
        url: "https://tramites.cobiene.com/",
        text: "Solicita tu convenio SITRACON",
        icon: faPaste,
      },
    ],
  },
  {
    image: ImgNorbertWiener,
    title: "NORBERT WIENER",
    benefits: [
      "CENTRO PREUNIVERSITARIO / CENTRO DE IDIOMAS:",
      "40% descuento por convenio.",
      "",
      "PREGRADO:",
      "10% de descuento en las carreras de obstetricia, enfermería, farmacia y bioquímica, odontología, tecnología médica en laboratorio clínico, anatomía patológica y terapia física.",
      "15% de descuento en las carreras de administración y negocios internacionales, contabilidad y auditoria, derecho y ciencia política, ingeniería industrial y gestión empresarial, ingeniería de sistemas e informática.",
      "",
      "BACHILLERATO:",
      "33% descuento por convenio.",
      "",
      "ALCANCE:",
      "Personal militar en actividad o retiro, personal civil en actividad o cesantes, así como sus familiares directos (cónyuge e hijos)",
      "- OO, SUP. TCOS. SSOO.  Tropa activo y Licenciado.",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [
      { url: "https://www.uwiener.edu.pe" },
      {
        url: "https://tramites.cobiene.com/",
        text: "Solicita tu convenio SITRACON",
        icon: faPaste,
      },
    ],
  },
  {
    image: ImgRicardoPalma,
    title: "RICARDO PALMA",
    benefits: [
      "CENTRO PRE UNIVERSITARIO:",
      "10 % de descuento sobre el ciclo .",
      "",
      "PREGRADO:",
      "Carrera de arquitectura y urbanismo escala 14, en el pago de las pensiones. ",
      "Carrera de medicina humana escala 9, en el pago de las pensiones.",
      "Carrera de administración y gerencia, administración de negocios globales, biología, contabilidad y finanzas, economía, hotelería y turismo, ingeniería civil, electrónica, industrial, informática, psicología, traducción e interpretación, escala 7.",
      "Oficiales del grado de coronel el descuento en el pago de pensiones es (de 5 cuotas pagan 4).",
      "Oficiales del grado de Teniente Coronel hasta Sub Oficiales de 3ra, personal civil e Hijos, el descuento en el pago de las pensiones será(de 5 cuotas pagan 3).",
      "",
      "POSGRADO:",
      "Maestría, doctorado, segunda especialización, descuento en el pago de las pensiones de 5 cuotas pagan 4",
      "",
      "ALCANCE:",
      "Personal militar en actividad o retiro, personal civil en actividad, así como sus familiares directos (cónyuge e hijos)",
      "- OO, SUP. TCOS. SSOO.  Tropa activo y Licenciado.",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [
      { url: "https://www.urp.edu.pe" },
      {
        url: "https://tramites.cobiene.com/",
        text: "Solicita tu convenio SITRACON",
        icon: faPaste,
      },
    ],
  },
  {
    image: ImgSanIngnacioLoyola,
    title: "SAN IGNACIO DE LOYOLA USIL",
    benefits: [
      "PREGRADO:",
      "La categoría mínima de (CATEGORIA A,) por única vez y si se conservará en los periodos académicos, en la medida que el rendimiento académico sea aprobatorio.",
      "10% y 13% de descuento en los diferentes programas académicos. En IE, en cualquiera de sus modalidades.",
      "Otorgará el descuento del 5% en cursos de duración de un mes, el 8% en cursos de duración de dos a tres meses y el 10% en cursos de duración de cuatro meses a más, sobre los precios de lista, ofrecidos en las instituciones educativas en cualquiera de sus modalidades.",
      "",
      "POSGRADO:",
      "15% de descuento, sobre los precios de lista, en los diferentes Programas Académicos ofrecidos en la EPG (maestría, doctorado, especializaciones, diplomados y formación continua), en cualquiera de sus modalidades en la Sede: La Molina – Campus 2.",
      "",
      "PROGRAMA ONLINE:",
      "15% de descuento, sobre los precios de lista, en los diferentes Programas Académicos ofrecidos en USIL ONLINE, en la Sede La Molina – Campus 2.",
      "",
      "ALCANCE:",
      "Personal militar en actividad o retiro, personal civil en actividad o cesante, así como sus familiares directos (cónyuge e hijos).",
      "- OO, SUP. TCOS. SSOO.  Tropa activo y Licenciado.",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [
      { url: "https://usil.edu.pe" },
      {
        url: "https://tramites.cobiene.com/",
        text: "Solicita tu convenio SITRACON",
        icon: faPaste,
      },
    ],
  },
  {
    image: ImgSanJuanBautista,
    title: "SAN JUAN BAUTISTA",
    benefits: [
      "PREGRADO: ",
      "Escala “C”: 25% de descuento en el pago de las pensiones en todas las carreras profesionales. Y en la modalidad semi presencial 15%.",
      "",
      "POSGRADO: ",
      "Escala “C”: 25 % de descuento en el pago de las pensiones.",
      "",
      "PROGRAMA DE ESTUDIO SEGUNDA ESPECIALIDAD EN ENFERMERIA YESTOMATOLOGÍA: ",
      "15% DE DESCUENTO",
      "",
      "CENTRO PRE UNIVERSITARIO: ",
      "20% DE DESCUENTO",
      "",
      "CENTRO DE IDIOMAS - CURSOS DE CAPACITACIÓN, DIPLOMADOS, SIMPOSIOS, PROGRAMAS DE PERFECCIONAMIENTO Y COMPLEMENTACIÓN ACADÉMICA PROFESIONAL. CULTURAL:",
      "Escala “C”: 25%",
      "",
      "CURSOS DE EXTENSIÓN:",
      "25% de descuento",
      "",
      "Descuento en derecho de admisión siempre que éste se realice en las instalaciones del Ejército con un número de 40 postulantes. El 100%.",
      "",
      "ALCANCE:",
      "Personal militar en actividad o retiro, Personal civil en actividad o cesante así como a familiares directos (cónyuge, hijos y hermanos)",
      "- OO, SUP. TCOS. SSOO.  Tropa activo y Licenciado.",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [
      { url: "https://www.upsjb.edu.pe" },
      {
        url: "https://tramites.cobiene.com/",
        text: "Solicita tu convenio SITRACON",
        icon: faPaste,
      },
    ],
  },
  {
    image: ImgSanMartin,
    title: "SAN MARTÍN DE PORRES",
    benefits: [
      "PREGRADO:",
      "Costo diferenciado en el pago de las pensiones en las diferentes carreras profesionales",
      "",
      "PROGRAMA PARA ADULTOS QUE TRABAJAN (PAT):",
      "15 % de descuento en el pago de las pensiones dirigido a oficiales",
      "20 % de descuento en el pago de las pensiones dirigido a Técnicos, suboficiales y personal civil",
      "",
      "POSGRADO:",
      "25 % de descuento en el pago de las diferentes carreras profesionales (maestría y doctorado)",
      "25% de descuento en segundas especializaciones.",
      "25% de descuentos en diplomados.",
      "",
      "ALCANCE:",
      "Personal militar en actividad o retiro, personal civil en actividad o cesante, así como sus familiares directos (cónyuge e hijos).\n",
      "- OO, SUP. TCOS. SSOO.  Tropa activo y Licenciado.",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [
      { url: "https://usmp.edu.pe" },
      {
        url: "https://tramites.cobiene.com/",
        text: "Solicita tu convenio SITRACON",
        icon: faPaste,
      },
    ],
  },
  {
    image: ImgSanMarcos,
    title: "NMSM FAC. CIENCIAS ECONOMICAS",
    benefits: [
      "POSGRADO:",
      "20 % de descuento en el costo total de diplomados, maestrías y doctorados a excepión del programa doble grado (sujeto a condiciones de universidades extranjeras.",
      "",
      "ALCANCE:",
      "Personal militar en actividad o retiro, personal civil en actividad o cesante, así como sus familiares directos (cónyuge e hijos).",
      "- OO, SUP. TCOS. SSOO.  Tropa activo y Licenciado.",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [
      { url: "https://economia.unmsm.edu.pe" },
      {
        url: "https://tramites.cobiene.com/",
        text: "Solicita tu convenio SITRACON",
        icon: faPaste,
      },
    ],
  },
  {
    image: ImgUtp,
    title: "UTP",
    benefits: [
      "PREGRADO:",
      "25 % de descuento en todas las carreras, en todas las sedes a nivel nacional.",
      "15% de descuento sobre el costo de pensiones en todas las carreras de pregrado, modalidad carreras para gente que trabaja, en todas las sedes a nivel nacional. ",
      "",
      "ALCANCE:",
      "Personal militar en actividad o retiro, personal civil en actividad o cesantes, así como sus familiares directos (cónyuge e hijos)",
      "- OO, SUP. TCOS. SSOO.  Tropa activo y Licenciado.",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [
      { url: "https://www.utp.edu.pe" },
      {
        url: "https://tramites.cobiene.com/",
        text: "Solicita tu convenio SITRACON",
        icon: faPaste,
      },
    ],
  },
  {
    image: ImgCatolicaSede,
    title: "CATÓLICA SEDE SAPIENTIAE",
    benefits: [
      "PREGRADO: \n",
      "Costos diferenciados en pensiones en las distintas carreras profesionales",
      "POSGRADO: \n",
      "Hasta el 20 % de descuento del costo total de los programas de Posgrado (maestrías y diplomados) a excepción del programa de doble grado.   \n",
      "ALCANCE:",
      "Personal militar en actividad\n" +
        "o retiro, personal civil en\n" +
        "actividad y cesante,\n" +
        "así como sus familiares\n" +
        "directos (cónyuge e hijos).\n",
    ],
    urlFile: UniversityConventionPdf,
    links: [
      { url: "https://www.ucss.edu.pe" },
      {
        url: "https://tramites.cobiene.com/",
        text: "Solicita tu convenio SITRACON",
        icon: faPaste,
      },
    ],
  },
  {
    image: ImgUnife,
    title: "UNIFÉ SAGRADO CORAZON",
    benefits: [
      "CENTRO PRE UNIFÉ:",
      "20 % descuento en el ciclo completo ",
      "",
      "PREGRADO:",
      "Personal de oficiales  Escala N° 28 en pensiones",
      "Personal de Tcos, SSOO actividad, retiro, familiares directos y civiles en actividad",
      "Escala N° 30 en pensiones",
      "",
      "PREGRADO SEGUNDA CARRERA",
      "Personal de Tcos, SSOO actividad, retiro, familiares directos y civiles en actividad, descuento del 15% en pensiones",
      "",
      "POSGRADO:",
      "Personal de oficiales 10% de descuento al cancelar ciclo completo (5 cuotas)",
      "Personal de Tcos y SSOO 15% descuento al cancelar ciclo completo (5 cuotas)",
      "",
      "SEGUNDA ESPECIALIDAD:",
      "Personal de oficiales 10% de descuento al cancelar ciclo completo (5 cuotas)",
      "Personal de Tcos y SSOO 15% descuento al cancelar ciclo completo (5 cuotas)",
      "",
      "DIPLOMADOS Y/O SEMINARIOS:",
      "Personal de oficiales escala N° 28 en el pago de las pensiones.",
      "Personal de Tcos y SSOO escala N° 30 en el pago de las pensiones.",
      "",
      "ALCANCE:",
      "Personal militar en actividad o retiro, personal civil en actividad, así como sus familiares directos (cónyuge e hijos)\n",
      "- OO, SUP. TCOS. SSOO.  Tropa activo y Licenciado.",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [
      { url: "https://www.unife.edu.pe" },
      {
        url: "https://tramites.cobiene.com/",
        text: "Solicita tu convenio SITRACON",
        icon: faPaste,
      },
    ],
  },
  {
    image: Norte,
    title: "PRIVADA DEL NORTE",
    alert:
      "Se completaron las vacantes para el beneficio del ejercito y su familia militar para el semestre 2023-1.",
    benefits: [
      "CARRERAS PREGRADO WA ONLINE: ",
      "30% de descuento confirmación de matrícula, colaboradores y familiares directos 15%.",
      "15 % de descuento en el pago de las pensiones en todas las carreras profesionales",
      "30% de descuento por ciclo académico, colaboradores y familiares directos 15%..",
      "",
      "CARRERAS PREGRADO WA ONLINE",
      "(CARRERAS A DISTANCIA)",
      "30% de descuento prematricula colaboradores y 15% familiares directos",
      "30% de descuento de matricula colaboradores y 15% familiares directos",
      "30% de descuento Cuotas por ciclo académico y 15% familiares directos",
      "",
      "EPEC ESCUELA DE POSGRADO) MBA, DIPLOMADOS, ESPECIALIZACIONES, CURSOS",
      "30 %de descuento en las pensiones de enseñanza y 15% familiares directos 15 % de descuento en el pago de las pensiones.",
      "",
      "ALCANCE:",
      "Personal militar en actividad o retiro, personal civil en actividad y cesante, así como sus familiares directos (cónyuge, hijos y hermanos)",
      "- OO, SUP. TCOS. SSOO.  Tropa activo y Licenciado.",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [
      { url: "https://www.upn.edu.pe" },
      {
        url: "https://tramites.cobiene.com/",
        text: "Solicita tu convenio SITRACON",
        icon: faPaste,
      },
    ],
  },
  {
    image: ImgConservatorio,
    title: "NACIONAL DE MÚSICA",
    benefits: [
      "PREGRADO\n",
      "Entre el 20% y 25 % en el pago de las pensiones en las carreras de Educación musical, dirección musical y artista profesional\n",
      "FORMACIÓN CONTINUA\n",
      "Curso básico para adultos (02 años) descuento, del 25% en el pago de las pensiones \n",
      "Curso básico para niños, descuento del 25% en el pago de las pensiones \n",
      "Cursos libres, descuento del 20% en el pago de las pensiones \n",
      "Cursos virtuales, descuento del 20% en el pago de las pensiones  \n",
      "ALCANCE:",
      "Personal militar en\n" +
        "actividad o retiro,\n" +
        "personal civil en actividad\n" +
        "o cesante,\n" +
        "así como sus familiares\n" +
        "directos (cónyuge, hijos y\n" +
        "hermanos)",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [
      { url: "http://www.unm.edu.pe/" },
      {
        url: "https://tramites.cobiene.com/",
        text: "Solicita tu convenio SITRACON",
        icon: faPaste,
      },
    ],
  },
  {
    image: ImgUniContinental,
    title: "Continental",
    benefits: [
      "MATRICULA:",
      "100 % de beneficio, sobre los costos por concepto de examen de admisión y matrícula, en todas las carreras de pregrado, en sus diferentes modalidades y en todas sus sedes a nivel nacional.",
      "",
      "PREGRADO:",
      " 10% de descuento sobre el costo de la pensión, en todas las carreras de pregrado, en sus diferentes modalidades de estudio y en todas sus sedes a nivel nacional.",
      "",
      "POSGRADO:",
      "10% de descuento sobre el costo de la pensión, en todos los programas de posgrado (formación continua, maestría), en cualquiera de sus modalidades de estudio y en todas sus sedes a nivel nacional.",
      "",
      "ESTUDIOS IN HOUSE:",
      "10% de descuento en denominado programa IN HOUSE, que contempla capacitaciones, dirigidas a un grupo de personas que soliciten un tema determinado de estudio.",
      "",
      "CENTRO DE IDIOMAS:",
      "17% de descuento sobre el costo de la pensión, en el Centro de Idiomas en las diferentes modalidades y sedes a nivel nacional.",
      "",
      "ALCANCE:",
      "personal militar en actividad o retiro, personal civil en actividad o cesantes, así como sus familiares directos (cónyuge e hijos)",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [
      { url: "https://ucontinental.edu.pe/" },
      {
        url: "https://tramites.cobiene.com/",
        text: "Solicita tu convenio SITRACON",
        icon: faPaste,
      },
    ],
  },
  {
    image: ImgUniversidadDelPacifico,
    title: "UP. CENTRO DE IDIOMAS",
    benefits: [
      "CENTRO DE IDIOMAS - CIDUP \n",
      "20 %  de descuento en el pago de las pensiones de los programas de idiomas \n",
      "20% de descuento en el pago de las pensiones de los programas de idiomas para niños o adolescentes\n",
      "ALCANCE:",
      "Personal militar en actividad o retiro, personal civil en actividad o cesantes, así como sus familiares directos (cónyuge e hijos)\n",
      "- OO, SUP. TCOS. SSOO.  Tropa activo y Licenciado.",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [
      { url: "https://www.up.edu.pe/" },
      {
        url: "https://tramites.cobiene.com/",
        text: "Solicita tu convenio SITRACON",
        icon: faPaste,
      },
    ],
  },
  // {
  //   image: ImgUniAnahuaca,
  //   title: "UNIVERSIDAD ANÁHUAC",
  //   benefits: [
  //     "70% DE BECA AL MEJOR ESTUDIANTE:\n",
  //     "OTORGAR EL BENEFICIO AL ESTUDIANTE DE EDUCACIÓN BASICA REGULAR (NIVEL SECUNDARIA)  QUE LOGRE CULMINAR EN SUS TRES AÑOS DE EDUCACIÓN SECUNDARIA, EN EL PRIMER PUESTO.\n",
  //     "50% DE BECA A LOS 02 MEJORES ESTUDIANTES:\n",
  //     "SI SE DETERMINA EN EL PROCESO DE EVALUACIÓN SON 02 LOS BENEFICIARIOS, SE OTORGARÁ EL BENEFICIO A LOS 02 ESTUDIANTES CON EL PORCENTAJE ESTABLECIDO Y QUE HALLAN LOGRADO CULMINAR EN SUS TRES AÑOS DE EDUCACIÓN SECUNDARIA CON EL PROMEDIO REQUERIDO.\n",
  //     "100% DE DESCUENTO POR DERECHO EN EL PROCESO DE ADMISIÓN A LOS ALUMNOS QUE OBTUVIERON LA BECA AL MEJOR ESTUDIANTE.\n",
  //     "50% DE DESCUENTO EN EL PROCESO DE ADMISIÓN, PARA ESTUDIANTES INTERESADOS EN FORMACIÓN DE PREGRADO\n",
  //     "ALCANCE:",
  //     "PARA ESTUDIANTES DE EDUCACION BÁSICA REGULAR (NIVEL SECUNDARIA) DE LAS INSTITUCIONES EDUCATIVAS DEL EJÉRCITO.\n",
  //     "- OO, SUP. TCOS. SSOO.  Tropa activo y Licenciado.",
  //   ],
  //   urlFile:
  //     "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
  //   links: [{ url: "https://www.anahuac.mx/" }],
  // },
  {
    title: "Autónoma",
    image: ImgUniAutonoma,
    benefits: [
      "PREGRADO REGULAR:",
      "Tarifas aplicables a la escala “D” en el pago de las pensiones en todas las carreras profesionales.",
      "",
      "POSGRADO",
      "Tarifas aplicables a la escala “B” en el pago de las pensiones de posgrado.",
      "",
      "CARRERAS PARA PERSONAS QUE TRABAJAN (CPT)",
      "Tarifas aplicables a la escala “C” en el pago de las pensiones pregrado, posgrado y educación continua.",
      "",
      "EDUCACIÓN CONTINUA",
      "10% dscto. (1 a 2 beneficiarios) de acuerdo a los matriculados.",
      "15% dscto. (3 a más beneficiarios) de acuerdo a los matriculados.\n",
      "",
      "Alcance:",
      "Personal militar en situación de actividad y retiro, personal civil en actividad o cesante, así como sus familiares directos (cónyuges e hijos); tropa servicio militar en actividad, licenciados.",
    ],
    links: [
      {
        url: "https://tramites.cobiene.com/",
        text: "Solicita tu convenio SITRACON",
        icon: faPaste,
      },
    ],
  },
  {
    title: "Anáhuac México",
    image: ImgUniAnahuaca,
    benefits: [
      "50% de descuento sobre el valor por derecho de Proceso de Admisión.",
      "PRE GRADO 50% de descuento sobre el pagó inicial a los alumnos de nuevo ingreso para licenciatura de su elección.",
      "50% en el pagó inicial para el ingreso de Enero asta el treinta de octubre del año en curso, así como para el ingreso de agosto asta el treinta de mayo del año en curso.",
      "",
      "Alcance:",
      "Para estudiantes de educación básica regular (nivel secundaria) de las instituciones educativas del ejército",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [
      { url: "https://www.anahuac.mx/" },
      {
        url: "https://tramites.cobiene.com/",
        text: "Solicita tu convenio SITRACON",
        icon: faPaste,
      },
    ],
  },
  {
    title: "CIENCIAS Y ARTES DE AMÉRICA LATINA",
    image: ImgUcal,
    benefits: [
      "PREGRADO:",
      "15% de descuento, sobre los costos por concepto de pensiones, para estudios de, en todas las carreras.",
      "",
      "POSGRADO: ",
      "15% de descuento, sobre los costos por concepto de pensiones, para estudios de MAESTRÍA. en cualquiera de sus modalidades.",
      "",
      "DIPLOMADOS Y CURSOS ESPECIALIZADOS:",
      "15% de descuento, sobre los costos por concepto de pensiones",
      "",
      "ALCANCE:",
      "Personal militar en situación de actividad y retiro, personal civil en actividad o cesante, así como sus familiares directos (cónyuge, hijos); tropa servicio militar en activid",
    ],
  },
  {
    title: "ESAN",
    image: Esan,
    benefits: [
      "CENTRO PRE UNIVERSITARIO:",
      "10 % de descuento en el pago de las pensiones.",
      "",
      "PREGRADO: ",
      "10 % de descuento en el pago de las pensiones.",
      "",
      "ALCANCE:",
      "Personal militar en situación de actividad y retiro, personal civil en actividad o cesante, así como sus familiares directos (cónyuge, hijos); tropa servicio militar en activid",
    ],
  },
  {
    title: "PRIVADA PERUANA ALEMANA",
    image: Upal,
    benefits: [
      "PREGRADO:",
      "Exoneración de matrícula",
      "25 % de descuento en pensiones en todas las carreras de pregrado; considerando las diferentes sedes e incluso si existiera a nivel nacional.",
      "40 % de descuento en programas de: formación continua y especializaciones, sobre el valor comercial del programa, considerando las diferentes sedes e incluso si existiera a nivel nacional.",
      "",
      "ALCANCE:",
      "Personal militar en actividad o retiro, Personal civil en actividad y cesante así como a familiares directos (cónyuge, hijos y hermanos)\n",
      "- OO, SUP. TCOS. SSOO.  Tropa activo y Licenciado.",
    ],
  },
  {
    title: "AUTONOMA DE ICA",
    image: Autonomaica,
    benefits: [
      "PREGRADO:",
      "Exoneración del pago del 100 % del costo de la matrícula.",
      "40 % de descuento en pensiones en todas las carreras de pregrado; considerando las diferentes sedes e incluso si existiera a nivel nacional.",
      "",
      "POSGRADO Y 2DA ESPECIALIZACIÓN:",
      "10 % de descuento, sobre el valor comercial del programa. Considerando las diferentes sedes e incluso si existiera a nivel nacional.",
      "",
      "ALCANCE:",
      "Personal militar en actividad o retiro, personal civil en actividad o cesante, así como sus familiares directos (cónyuge e hijos). tropa servicio militar en actividad, licenciados.",
    ],
  },
  {
    title: "Newman",
    image: Newman,
    benefits: [
      "5% de descuento sobre los descuentos interesados en cursar Maestrías Oficiales online de “NEWMAN”, El descuento se aplicará sobre las tarifas vigentes para Perú.",
      "Sobre la tarifa que tiene cada uno de las maestrías se aplicará el descuento comercial que exista en el momento de la reserva y se añadirá el descuento adicional por ser beneficiario del convenio. Ejemplo si un máster de “NEWMAN el descuento comercial es de un 45% al postulante se le aplicara un descuento total del 50% (45% de descuento comercial más + 5% de descuento por convenio). El descuento total puede alcanzar hasta el 60% dependiendo de la titulación y casa de estudio.",
      "",
      "ALCANCE:",
      "Personal militar en actividad o retiro, personal civil en actividad o cesante, así como sus familiares directos (cónyuge e hijos). tropa servicio militar en actividad, licenciados.",
    ],
  },
  {
    title: "INTERNACIONAL DE LA RIOJA",
    image: Unir,
    benefits: [
      "5% sobre los descuentos oficiales que tenga en ese momento, a los beneficiarios de EL EJÉRCITO interesados en cursar Maestrías Oficiales online de “UNIR”, El descuento se aplicará sobre las tarifas vigentes para Perú.",
      "Sobre la tarifa que tiene cada uno de las maestrías se aplicará el descuento comercial que exista en el momento de la reserva y se añadirá el descuento adicional por ser beneficiario del convenio. Ejemplo si un máster de “UNIR” el descuento comercial es de un 45% al postulante se le aplicara un descuento total del 50% y 45% de descuento comercial más + 5% de descuento por convenio). El descuento total puede alcanzar hasta el 60% dependiendo de la titulación y casa de estudio.",
      "",
      "ALCANCE:",
      "Personal militar en actividad o retiro, personal civil en actividad o cesante, así como sus familiares directos (cónyuge e hijos). tropa servicio militar en actividad, licenciados.",
    ],
  },
  {
    title: "CAYETANO HEREDIA",
    image: Cayetano,
    benefits: [
      "PREGRADO:",
      "10% DSCTO EN LAS CARRERAS DE MEDICINA Y ESTOMATOLOGIA",
      "15% DSCTO EN LAS CARRERAS DE FARMACIA Y BIOQUIMICA, NUTRICION, MEDICINA VETERINARIA Y ZOOTECNIA.",
      "20% DSCTO EN LA CARRERA DE BIOLOGIA",
      "25% DSCTO EN LAS CARRERAS DE INGENIERIA AMBIENTAL, INGENIERIA INFORMATICA, ADMINISTRACION, EDUCACION, PSICOLOGIA",
      "15% DSCTO EN EDUCACION CONTINUA, MAESTRIAS Y DOCTORADOS.",
      "20% DSCTO EN IDIOMAS INGLES Y PORTUGUES",
      "",
      "ALCANCE:",
      "Personal militar en actividad o retiro, personal civil en actividad o cesantes, así como a familiares directos (cónyuge, hijos y hermanos) tropa servicio militar en actividad, licenciados.",
    ],
  },
  {
    title: "DE LIMA",
    image: Unilima,
    benefits: [
      "POSGRADO:",
      "10% En programas de doctorado.",
      "15% En programas de maestría.",
      "",
      "CURSOS DE EXTENSION Y ESPECIALIZACIÓN:",
      "15% Sobre el valor de los cursos de extensión y especialización que brinda la dirección de educación continua.",
      "",
      "ALCANCE:",
      "Personal militar en actividad o retiro, personal civil en actividad o cesantes, así como a familiares directos (cónyuge, hijos y hermanos) tropa servicio militar en actividad, licenciados.",
    ],
  },
  {
    title: "DE LIMA",
    image: Uprit,
    benefits: [
      "PREGRADO:",
      "25% DSCTO EN EL PAGO DE PENSIONES",
      "",
      "POSGRADO:",
      "25% EN PROGRAMAS DE MAESTRÍA Y DOCTORADO ",
      "",
      "CURSOS DE EXTENSION Y ESPECIALIZACIÓN:",
      "25% Sobre el valor de los cursos de extensión y especialización que brinda la dirección de educación continua.",
      "",
      "ALCANCE:",
      "Personal militar en actividad o retiro, personal civil en actividad o cesantes, así como a familiares directos (cónyuge, hijos y hermanos) tropa servicio militar en actividad, licenciados.",
    ],
  },
  // {
  //   title: "CONSERVATORIO DE LIMA",
  //   image: ImgConserLima,
  //   benefits: [
  //     "PREGRADO:",
  //     "Entre el 20% y 25 % en el pago de las pensiones en las carreras de Educación musical, dirección musical y" +
  //       " artista profesional\n",
  //     "ALCANCE:",
  //     "Personal militar en situación\n" +
  //       "de actividad y retiro,\n" +
  //       "personal civil en actividad o\n" +
  //       "cesante, así como sus\n" +
  //       "familiares directos\n" +
  //       "(cónyuge, hijos); tropa\n" +
  //       "servicio militar en activid\n",
  //   ],
  // },
];
