import {
  Logo1,
  Logo10,
  Logo11,
  Logo12,
  Logo13,
  Logo14,
  Logo15,
  Logo16,
  Logo17,
  Logo18,
  Logo19,
  Logo2,
  Logo21,
  Logo3,
  Logo4,
  Logo5,
  ImgFedericoVidarreal,
  Logo7,
  Logo8,
  Logo9,
  Norte,
} from "../images";

export const universities = [
  {
    image: Logo1,
    title: "AGRARIA LA MOLINA",
    benefits: [
      "TARIFA PREFERENCIAL EN CURSOS DE CAPACITACIÓN Y EXTENSIÓN",
      "BECA PARA HIJOS DEL PERSONAL DEL COBIENE Y CIVIL DEL COBIENE FALLECIDO EN ACCIÓN DE ARMAS O ACTO DE SERVICIO EN LA LUCHA CONTRA EL TERRORISMO O NARCOTRÁFICO, PREVIA ADMISION, EVALUACION SOCIOECONOMICA Y DISPONIBILIDAD DE LA OFICINA COMPETENTE DE LA UNALM.",
      "TARIFA PREFERENCIAL EN LA PRE-AGRARIA",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
  },
  {
    image: Logo2,
    title: "CIENTÍFICA DEL SUR",
    benefits: [
      "DESCUENTO DEL 40% PARA LAS CARRERAS DE MEDICINA HUMANA, ENFERMERÍA Y OBSTETRICIA Y 60% DE DESCUENTO PARA LAS CARRERAS DE VETERINARIA Y ZOOTECNIA, ESTOMATOLOGÍA, ING. ECONÓMICA, COMUNICACIÓN, ING. AMBIENTAL, ING. AGROFORESTAL, ARQUITECTURA, ARTES ESCÉNICAS, BIOLOGÍA MARINA, NUTRICIÓN Y DIETÉTICA, PSICOLOGÍA, TURISMO SOSTENIBLE Y HOTELERÍA, NEGOCIOS SOSTENIBLES ING. DE SISTEMAS EMPRESARIALES, DERECHO, ING. DE ALIMENTOS, FARMACIA Y BIOQUÍMICA, SOBRE LA ESCALA “E” (NIVEL 1), APLICADAS A LAS ARMADAS MENSUALES.",
      "DESCUENTO DEL 30% EN LAS CARRERAS PROFESIONALES PARA LAS PERSONAS QUE TRABAJAN Y EL 30% DE DESCUENTO EN LOS CURSOS DE FORMACIÓN CONTINUA. DESCUENTO DEL 10% EN MAESTRÍAS Y ESPECIALIZACIONES Y EL 15% DE DESCUENTO EN EL CENTRO DE IDIOMAS (INGLES – PORTUGUÉS)",
      "DOS (02) MEDIAS BECAS ANUALES EN PRE GRADO.",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
  },
  {
    image: Logo3,
    title: "CATÓLICA DEL PERÚ",
    benefits: [
      "PRE GRADO : UBICA AL ALUMNO EN ESCALA DE PAGOS SEGÚN ESTUDIO REALIZADO EN LA UNIVERSIDAD.",
      "LOS HIJOS DE PERSONAL COBIENE FALLECIDO O DISCAPACITADO PODRÁN POSTULAR A SU PROGRAMA DE 'BECAS POR SITUACIÓN ESPECIAL'",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
  },
  {
    image: Logo4,
    title: "CESAR VALLEJO",
    benefits: [
      "CATEGORIA ESPECIAL UCV – LIMA NORTE  S/.400.00",
      "CATEGORIA ESPECIAL UCV – LIMA ESTE   S/.350.00",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
  },
  {
    image: Logo5,
    title: "ESAN",
    benefits: [
      "10% DE DSCTO PARA ESTUDIOS EN SU CENTRO PRE UNV Y EN PRE GRADO",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
  },
  {
    image: ImgFedericoVidarreal,
    title: "FEDERICO VILLARREAL",
    benefits: [
      "25% DE DSCTO  EN MAESTRÍAS Y DOCTORADOS (sólo titulares en actividad)",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
  },
  {
    image: Logo7,
    title: "JAIME BAUSATE Y MESA",
    benefits: [
      "20% DE DSCTO  EN EL PAGO DE MATRICULA Y PENSIÓN(PERIODISMO) SOLO PRE-GRAD",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
  },
  {
    image: Logo8,
    title: "MARCELINO CHAMPAGNAT",
    benefits: [
      "10% DE DSCTO EN  PRE GRADO Y POST GRADO",
      "30% DE DSCTO EN CENTRO PRE UNIV.",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
  },
  {
    image: Logo9,
    title: "NORBERT WIENER",
    benefits: [
      "10% Y 15% DE DSCTO EN PENSIONES SEGÚN CARRERA DESDE EL INGRESO",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
  },
  {
    image: Logo10,
    title: "DEL PACIFICO",
    benefits: [
      "INCORPORAR EN EL SISTEMA DE ESCALA DE PENSIONES DE LA UNIVERSIDAD DESDE EL MOMENTO DE INGRESO, COMO ALUMNO DE PREGRADO LA UBICACIÓN EN LA ESCALA DE PAGOS, SE DETERMINA DE ACUERDO A LOS RESULTADOS DEL ANÁLISIS QUE REALICE LA GERENCIA DE PENSIONES",
      "TARIFA PREFERENCIAL DEL 20 % DE DSCTO  EN EL CENTRO IDIOMAS.",
      "SI LUEGO DE INGRESAR A LA UNIVERSIDAD (PREGRADO), EL ALUMNO PIERDE A SU PADRE O QUEDAN EN ESTADO DE DISCAPACIDAD, EL ALUMNO PUEDE SOLICITAR LA REVISIÓN DE LA ESCALA A LA GERENCIA DE PENSIONES.",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
  },
  {
    image: Logo11,
    title: "RICARDO PALMA",
    benefits: [
      "CATEGORIZACIÓN A ESCALA MÍNIMA  EN PRE Y POST - GRADO",
      "CRLS DE 05 CUOTAS PAGAN 04 DE TTE CRL A SO3 Y EECC DE 05 CUOTAS PAGAN 03",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
  },
  {
    image: Logo12,
    title: "SAN IGNACIO DE LOYOLA USIL",
    benefits: [
      "OTORGARA LA CATEGORIA MINIMA (CATEGORIA “A”) DE PENSIONES EN EL PROGRAMA DE PRE GRADO",
      "EL BENEFICIO SE CONSIDERARA UNA SOLA VEZ  Y SE CONSERVARA EN LA MEDIDA QUE EL ALUMNO MANTENGA UN BUEN RENDIMIENTO ACADEMICO, QUEDANDO ESTABLECIDO QUE EL ALUMNO QUE HAYA REPROBADO UNO O MAS CURSOS NO SE LE CONSEDERA NUEVAMENTE DICHO BENEFICIO, AUNQUE LOS SIGUIENTES PERIODOS TENGA NOTA APROBATORIA.",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
  },
  {
    image: Logo13,
    title: "SAN JUAN BAUTISTA",
    benefits: [
      "25% DE DSCTO EN LAS  PENSIONES, VARIA DE ACUERDO A LA CARRERA PROFESIONAL. EN PRE-POST GRADO  ",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
  },
  {
    image: Logo14,
    title: "SAN MARTÍN DE PORRES",
    benefits: [
      "PRE GRADO: ESTABLECE ESCALAS DIFERENCIADAS PARA PERSONAL COBIENE Y CIVIL. LA UNIVERSIDAD INFORMA ANUALMENTE LAS VARIACIONES  EN LOS COSTOS DE CADA ESCALA.",
      "ALCANCE: PERSONAL COBIENE EN ACTIVIDAD O RETIRO E HIJOS, EMPLEADOS CIVILES EN ACTIVIDAD E HIJOS.",
      "POST GRADO: OTORGA 25% DE DESCUENTO PARA ESTUDIOS DE MAESTRÍAS, DOCTORADOS  Y SEGUNDA ESPECIALIZACIÓN.",
      "SEDES :  SANTA ANITA, LA MOLINA, SURQUILLO Y JESÚS MARÍA.",
      "PRÓRROGA AUTOMÁTICA",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
  },
  {
    image: Logo15,
    title: "SAN MARCOS FACULTAD C.C. ECONOMICAS",
    benefits: [
      "20% DEL COSTO TOTAL DEL PROGRAMA DE POSTGRADO QUE DESEEN CURSAR (DOCTORADO, MAESTRÍA Y DIPLOMADOS) A EXCEPCIÓN AL PROGRAMA DE DOBLE GRADO, CUYAS TARIFAS ESTÁN SUJETAS A LAS CONDICIONES QUE ESTABLECEN LAS UNIVERSIDADES EXTRANJERAS Y QUE NO DEPENDEN DE LA UNMSM",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
  },
  {
    image: Logo16,
    title: "SEÑOR DE SIPAN",
    benefits: [
      "20% EN MENSUALIDADES DE PENSIONES EN TODAS LAS CARRERAS (MODALIDAD A DISTANCIA) PRE - GRADO",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
  },
  {
    image: Logo17,
    title: "UTP",
    benefits: [
      "25% DE DSCTO  EN EL PAGO DE PENSIONES EN EL PAGO EN PRE-POST GRAD",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
  },
  {
    image: Logo18,
    title: "CATOLICA SEDE SAPIENTIAE",
    benefits: [
      "ENTRE EL 25% AL 27% DE DESCUENTO DE ACUERDO A LAS CARRERAS) PARA ESTUDIOS DE PREGRADO.",
      "20% DEL COSTO TOTAL DEL PROGRAMA DE POSTGRADO (MAESTRÍAS Y DIPLOMADOS) A EXCEPCIÓN AL PROGRAMA DE DOBLE GRADO.",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
  },
  {
    image: Logo19,
    title: "UNIFE SAGRADO CORAZON",
    benefits: [
      "PERSONAL OFICIALES (ACTIVIDAD Y RETIRO), Y FAMILIARES DIRECTOS (CÓNYUGE E HIJOS), SERÁN ASIGNADOS EN LA ESCALA Nº 28 (S/.890.00) Y PARA EL PERSONAL SUPERVISORES, TÉCNICOS Y SUBOFICIAL (ACTIVIDAD Y RETIRO) Y CIVILES EN ACTIVIDAD, EN AMBOS CASOS FAMILIARES DIRECTOS (CÓNYUGE E HIJOS), SERÁN ASIGNADOS EN LA ESCALA Nº 30 (S/.660.00), CABE RESALTAR QUE EL PAGO DE LAS PENSIONES DE ESTUDIO PARA EL PÚBLICO EN GENERAL ES DE (S/. 2500.00)",
      "DESCUENTO DEL 20% AL CANCELAR EL CICLO COMPLETO DE ESTUDIOS EN EL CENTRO PRE UNIFÉ.",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
  },
  {
    image: Norte,
    title: "UNIV. PRIVADA DEL NORTE",
    benefits: [
      "15% DE DESCUENTO EN LAS DIFERENTES CARRERAS PROFESIONALES DE PREGRADO.",
      "15% DE DESCUENTO, EN LAS DIFERENTES CARRERAS PROFESIONALES DE PREGRADO EN EL PROGRAMA WORKING ADULTO",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
  },
  {
    image: Logo21,
    title: "UNIV. PERUANA DE CIENCIAS APLICADAS UPC ",
    benefits: [
      "ESCALA MÍNIMA DE PENSIONES PARA LAS DIFERENTES CARRERAS PROFESIONALES DE PREGRADO, PROGRAMA DE ESTUDIOS PROFESIONALES PARA EJECUTIVOS (EPE) Y GENTE  QUE TRABAJA (EPE). (SOLO INGRESANTES A PARTIR DEL AF 2020)",
      "OTORGAR LOS DESCUENTOS VIGENTES DETALLADOS EN LA POLÍTICA DE DESCUENTOS DE LA ESCUELA DE POSTGRADO - UPC EN CURSOS Y/O PROGRAMAS EDUCATIVOS SEGÚN CORRESPONDA.",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
  },
];
