import {
  ImgCatolicaSede,
  ImgCesarVallejo,
  ImgCientificaDelSur,
  ImgConservatorio,
  ImgEsan,
  ImgFedericoVidarreal,
  ImgJaimeBausate,
  ImgMarcelinoChampagnat,
  ImgNorbertWiener,
  ImgRicardoPalma,
  ImgSanIngnacioLoyola,
  ImgSanJuanBautista,
  ImgSanMarcos,
  ImgSanMartin,
  ImgSeniorSipan,
  ImgUnife,
  ImgUniversidadDelPacifico,
  ImgUpc,
  ImgUtp,
  Norte,
} from "../images";

export const universities = [
  {
    image: ImgUpc,
    title: "UPC",
    benefits: [
      "PREGRADO: \n",
      "Escala mínima de pensiones en diferentes carreras y programa de estudios profesionales para ejecutivos (EPE). \n",
      "ALCANCE:",
      "Personal militar en actividad o retiro, personal civil en actividad y cesante, así como sus familiares directos (cónyuge, hijos y hermanos)",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [
      {
        url: "https://www.utp.edu.pe",
      },
    ],
  },
  {
    image: ImgCientificaDelSur,
    title: "CIENTÍFICA DEL SUR",
    benefits: [
      "CENTRO DE IDIOMAS (CIDIO) \n",
      "15 % de descuento en el pago de las pensiones de inglés y portugués\n",
      "PREGRADO: \n",
      "40 % de descuento en pago de las pensiones en carreras de enfermería, obstetricia y medicina humana, sobre la escala E\n",
      "60% de descuento en pago de las pensiones en las otras carreras, sobre la escala E \n",
      "CARRERAS PARA LAS PERSONAS QUE TRABAJAN (CPE) \n",
      "30 %  de descuento en el pago de las pensiones, Administración de empresas, Ingeniería de sistemas, Derecho, Psicología, Comunicación y publicidad, Nutrición y dietética\n",
      "POSGRADO: \n",
      "10 % de descuento en maestría y especializaciones \n",
      "FORMACIÓN CONTINUA\n",
      "30% descuento en el pago de las pensiones de los cursos \n",
      "ALCANCE:",
      "Personal militar en actividad o retiro, personal civil en actividad y cesante, así como sus familiares directos (cónyuge, hijos y hermanos)",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [{ url: "https://www.cientifica.edu.pe" }],
  },

  {
    image: ImgCesarVallejo,
    title: "CESAR VALLEJO",
    benefits: [
      "PREGRADO: \n",
      "Categoría 3 en pensiones para todas las carreras profesionales.\n",
      "POSGRADO: \n",
      "Categoría 2 en pensiones para estudios de maestrías\n",
      "PROGRAMA FORMACIÓN ADULTOS: \n",
      "Categoría 2 en pensiones en todas las carreras profesionales\n",
      "5% descuento por pago anticipado a estudiantes regulares \n",
      "ALCANCE:",
      "Personal militar en situación de actividad y retiro, personal civil en actividad o cesantes, así como sus familiares directos (cónyuge , hijos, padres y hermanos en caso de ser trabajadores solteros)",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [{ url: "https://www.ucv.edu.pe" }],
  },
  {
    image: ImgEsan,
    title: "ESAN",
    benefits: [
      "CENTRO PRE UNIVERSITARIO: \n",
      "10 % de descuento en el pago de las pensiones  \n",
      "PREGRADO: \n",
      "10 % de descuento en el pago de las pensiones  \n",
      "ALCANCE:",
      "Personal militar en actividad o retiro, así como sus familiares directos (cónyuge e hijos)\n",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [{ url: "https://www.ue.edu.pe" }],
  },
  {
    image: ImgFedericoVidarreal,
    title: "FEDERICO VILLARREAL",
    benefits: [
      "POS GRADO:",
      "25 % de descuento en matrícula y pensiones en los diferentes  maestrías y doctorados",
      "ALCANCE:",
      "Personal militar en actividad",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [{ url: "http://www.unfv.edu.pe" }],
  },
  {
    image: ImgJaimeBausate,
    title: "JAIME BAUSATE Y MEZA",
    benefits: [
      "PREGRADO\n",
      "20 % de descuento sobre el costo de la pensión en las carreras de periodismo, escuela profesional de comunicación audiovisual.\n",
      "POSGRADO \n",
      "20 % de descuento sobre el costo de la pensión en enseñanza de posgrado, diplomados y curso de proyección social.\n",
      "ALCANCE:",
      "personal militar en actividad o retiro, personal civil en actividad o cesantes, así como a familiares directos (cónyuge, hijos y hermanos)\n",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [{ url: "http://bausate.edu.pe" }],
  },
  {
    image: ImgMarcelinoChampagnat,
    title: "MARCELINO CHAMPAGNAT",
    benefits: [
      "PREGRADO: ",
      "10 % de descuento en el pago de las pensiones en las carreras de administración, psicología y contabilidad",
      "POSGRADO",
      "10% de descuento en el pago de las pensiones en maestría y doctorado. ",
      "ALCANCE:",
      "Personal militar en actividad o retiro, Personal civil en actividad y cesante así como a familiares directos (cónyuge, hijos y hermanos)\n",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [{ url: "https://umch.edu.pe" }],
  },
  {
    image: ImgNorbertWiener,
    title: "NORBERT WIENER",
    benefits: [
      "CENTRO PREUNIVERSITARIO\n",
      "costo diferenciado por convenio \n",
      "CENTRO DE IDIOMAS\n",
      "costo diferenciado por convenio \n",
      "PREGRADO\n",
      "10% de descuento en las carreras de obstetricia, enfermería, farmacia y bioquímica, odontología, tecnología médica en laboratorio clínico, anatomía patológica y terapia física.\n",
      "15% de descuento en las carreras de administración y negocios internacionales, contabilidad y auditoria, derecho y ciencia política, ingeniería industrial y gestión empresarial, ingeniería de sistemas e informática.\n",
      "ALCANCE:",
      "Personal militar en actividad o retiro, personal civil en actividad o cesantes, así como sus familiares directos (cónyuge e hijos)\n",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [{ url: "https://www.uwiener.edu.pe" }],
  },
  {
    image: ImgUniversidadDelPacifico,
    title: "UNIVERSIDAD DEL PACIFICO",
    benefits: [
      "CENTRO DE IDIOMAS - CIDUP \n",
      "20 %  de descuento en el pago de las pensiones de los programas de idiomas \n",
      "20% de descuento en el pago de las pensiones de los programas de idiomas para niños o adolescentes\n",
      "ALCANCE:",
      "Personal militar en actividad o retiro, personal civil en actividad o cesantes, así como sus familiares directos (cónyuge e hijos)\n",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [{ url: "https://www.up.edu.pe/" }],
  },
  {
    image: ImgRicardoPalma,
    title: "RICARDO PALMA",
    benefits: [
      "CENTRO PRE UNIVERSITARIO: \n",
      "10 % de descuento sobre el ciclo  \n",
      "PREGRADO\n",
      "Carrera de arquitectura y urbanismo escala 14, en el pago de las pensiones \n",
      "Carrera de medicina humana escala 9, en el pago de las pensiones \n",
      "Carrera de administración y gerencia, administración de negocios globales, biología, contabilidad y finanzas, economía, hotelería y turismo, ingeniería civil, electrónica, industrial, informática, psicología, traducción e interpretación, escala 7\n",
      "Oficiales del grado de coronel el descuento en el pago de pensiones es (de 5 cuotas pagan 4)\n",
      "Oficiales del grado de Teniente Coronel hasta Sub Oficiales de 3ra, personal civil e Hijos, el descuento en el pago de las pensiones será(de 5 cuotas pagan 3) \n",
      "POSGRADO\n",
      "Maestría, doctorado, segunda especialización, descuento en el pago de las pensiones de 4 cuotas pagan 3",
      "ALCANCE:",
      "Personal militar en actividad o retiro, personal civil en actividad, así como sus familiares directos (cónyuge e hijos)",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [{ url: "https://www.urp.edu.pe" }],
  },
  {
    image: ImgSanIngnacioLoyola,
    title: "SAN IGNACIO DE LOYOLA USIL",
    benefits: [
      "PREGRADO: \n",
      "Escala mínima de pensiones – CATEGORIA A, por única vez y si se conservará en los periodos académicos, en la medida  que el rendimiento académico  se aprobatorio .\n",
      "POSGRADO: \n",
      "15% de descuento, sobre los precios de lista, en los diferentes Programas Académicos ofrecidos en la EPG (maestría, doctorado, especializaciones, diplomados y formación continua), en cualquiera de sus modalidades en la Sede La Molina – Campus 2\n",
      "PROGRAMA ONLINE: \n",
      "15% de descuento, sobre los precios de lista, en los diferentes Programas Académicos ofrecidos en USIL ONLIFE, en la Sede La Molina – Campus 2\n",
      "ALCANCE:",
      "Personal militar en actividad o retiro, personal civil en actividad o cesante, así como sus familiares directos (cónyuge e hijos).",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [{ url: "https://usil.edu.pe" }],
  },
  {
    image: ImgSanJuanBautista,
    title: "SAN JUAN BAUTISTA",
    benefits: [
      "PREGRADO: \n" +
        "25% de descuento en el pago de las pensiones en todas las carreras profesionales \n",
      "PROGRAMA ESPECIAL PARA ADULTOS  \n",
      "25% de descuento en el pago de las pensiones de carreras de contabilidad y administración \n",
      "POSGRADO: \n",
      "25 %  de descuento en el pago de las pensiones en maestría en gestión pública, maestría en  gestión estratégica, maestría en derecho civil y comercial  \n" +
        " ",
      "CENTRO DE IDIOMAS - CURSOS DE EXTENSIÓN Y DIPLOMADOS. \n",
      "50 % de descuento en el pago de las pensiones de los diferentes cursos de idiomas\n",
      "CURSOS DE EXTENSIÓN \n",
      "50% de descuento en el pago de las pensiones en todos los cursos",
      "ALCANCE:",
      "Personal militar en actividad o retiro, Personal civil en actividad o cesante así como a familiares directos (cónyuge, hijos y hermanos)",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [{ url: "https://www.upsjb.edu.pe" }],
  },
  {
    image: ImgSanMartin,
    title: "SAN MARTÍN DE PORRES",
    benefits: [
      "PREGRADO: \n",
      "Costo diferenciado en el pago de las pensiones en las diferentes carreras profesionales\n",
      "PROGRAMA PARA ADULTOS QUE TRABAJAN (PAT): \n",
      "15 % de descuento en el pago de las pensiones dirigido a oficiales \n",
      "20 % de descuento en el pago de las pensiones dirigido a Técnicos, suboficiales y personal civil \n",
      "POSGRADO: \n",
      "25 % de descuento en el pago de las diferentes carreras profesionales (maestría y doctorado)\n",
      "25% de descuento en segundas especializaciones \n",
      "25% de descuentos en diplomados \n",
      "ALCANCE:",
      "Personal militar en actividad o retiro, personal civil en actividad o cesante, así como sus familiares directos (cónyuge e hijos).\n",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [{ url: "https://usmp.edu.pe" }],
  },
  {
    image: ImgSanMarcos,
    title: "UNMSM FAC. CIENCIAS ECONOMICAS",
    benefits: [
      "POSGRADO:\n",
      "20 % de descuento en el costo total de diplomados, maestrías y doctorados\n",
      "ALCANCE:",
      "Personal militar en actividad o retiro, personal civil en actividad o cesante, así como sus familiares directos (cónyuge e hijos).\n",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [{ url: "https://economia.unmsm.edu.pe" }],
  },
  {
    image: ImgSeniorSipan,
    title: "SEÑOR DE SIPAN",
    benefits: [
      "PREGRADO: \n",
      "Categoría(04), descuento en las pensiones en todas las carreras (a excepción de medicina humana, estomatología y enfermería)\n",
      "POSGRADO:\n",
      "20 % de descuento en las pensiones\n",
      "ALCANCE:",
      "Personal militar en actividad o retiro, personal civil en actividad o cesantes, así como sus familiares directos (cónyuge e hijos)\n",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [{ url: "https://www.uss.edu.pe" }],
  },
  {
    image: ImgUtp,
    title: "UTP",
    benefits: [
      "PREGRADO\n",
      "25 % de descuento en todas las carreras, en todas las sedes a nivel nacional. \n",
      "ALCANCE:",
      "Personal militar en actividad o retiro, personal civil en actividad o cesantes, así como sus familiares directos (cónyuge e hijos)\n",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [{ url: "https://www.utp.edu.pe" }],
  },
  {
    image: ImgCatolicaSede,
    title: "CATOLICA SEDE SAPIENTIAE",
    benefits: [
      "PREGRADO: \n",
      "Costos diferenciados en pensiones en las distintas carreras profesionales  \n",
      "POSGRADO: \n",
      "Hasta el 20 % de descuento del costo total de los programas de posgrado (maestrías y diplomados) a excepción del programa de doble grado.  \n",
      "ALCANCE:",
      "Personal militar en actividad o retiro, personal civil en actividad y cesante, así como sus familiares directos (cónyuge e hijos)",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [{ url: "https://www.ucss.edu.pe" }],
  },
  {
    image: ImgUnife,
    title: "UNIFE SAGRADO CORAZON",
    benefits: [
      "CENTRO PRE UNIFÉ: \n",
      "20 % descuento en el ciclo completo  \n",
      "PREGRADO: \n" + "Personal de oficiales  Escala N° 28 en pensiones \n",
      "Personal de Tcos y SSOO Escala N° 30 en pensiones  \n",
      "PREGRADO SEGUNDA CARRERA\n",
      "Personal de oficiales  Escala N° 28 en pensiones \n",
      "Personal de Tcos y SSOO Escala N° 30 en pensiones  \n",
      "POSGRADO  \n",
      "Personal de oficiales 10% de descuento al cancelar ciclo completo (5 cuotas)\n",
      "Personal de Tcos y SSOO 15% descuento al cancelar ciclo completo (5 cuotas)\n",
      "SEGUNDA ESPECIALIDAD\n",
      "Personal de oficiales 10% de descuento al cancelar ciclo completo (5 cuotas)\n",
      "Personal de Tcos y SSOO 15% descuento al cancelar ciclo completo (5 cuotas)\n",
      "DIPLOMADOS Y/O SEMINARIOS\n",
      "Personal de oficiales escala N° 28 en el pago de las pensiones \n",
      "Personal de Tcos y SSOO escala N° 30 en el pago de las pensiones \n",
      "ALCANCE:",
      "Personal militar en actividad o retiro, personal civil en actividad, así como sus familiares directos (cónyuge e hijos)\n",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [{ url: "https://www.unife.edu.pe" }],
  },
  {
    image: Norte,
    title: "UNIV. PRIVADA DEL NORTE",
    benefits: [
      "PREGRADO: \n",
      "15 % de descuento en el pago de las pensiones en todas las carreras profesionales \n",
      "PROGRAMA WORKING ADULTO ",
      "15 % de descuento en el pago de las pensiones \n",
      "ALCANCE:",
      "Personal militar en actividad o retiro, personal civil en actividad y cesante, así como sus familiares directos (cónyuge, hijos y hermanos)",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [{ url: "https://www.upn.edu.pe" }],
  },
  {
    image: ImgConservatorio,
    title: "UNIV. NACIONAL DE MÚSICA",
    benefits: [
      "PREGRADO\n",
      "Entre el 20% y 25 % en el pago de las pensiones en las carreras de Educación musical, dirección musical y artista profesional\n",
      "FORMACIÓN CONTINUA\n",
      "Curso básico para adultos (02 años) descuento, del 25% en el pago de las pensiones \n",
      "Curso básico para niños, descuento del 25% en el pago de las pensiones \n",
      "Cursos libres, descuento del 20% en el pago de las pensiones \n",
      "Cursos virtuales, descuento del 20% en el pago de las pensiones  \n",
      "ALCANCE:",
      "Personal militar en actividad o retiro, personal civil en actividad o cesante, así como sus familiares directos (cónyuge, hijos y hermanos)",
    ],
    urlFile:
      "https://drive.google.com/file/d/1E9wVieCur8Alr6B-XKSaF4tiTTFJQcHg/view?usp=sharing",
    links: [{ url: "http://www.unm.edu.pe/" }],
  },
];
